---
engine: knitr
title: "Projets en 2015"
format: 
    html:
        toc: true
---

### Programme d’Appui au programme National d’Investissement de l’Agriculture du Sénégal (PAPSEN)/Evaluation de l’impact potentiel des changements climatiques sur le cycle de l’eau à partir des scénarios du CMIP5 (Associé à l'Université Gaston Berger / Janvier 2015 - Janvier 2017)
Calage-validation d’un modèle hydrologique sur le bassin versant de la Casamance à Kolda et assimilation des scénarios CMIP5 du dernier rapport du GIEC de 2013 dans le modèle hydrologique pour faire des projection sur les ressources en eau du bassin à l’horizon 2035.

## Projet de gestion intégrée des Zones Côtières (PGIZC)/Etude bathymétrique dans le Gandiolais (Associé à l'Université Gaston Berger / Janvier 2015 - Janvier 2016)
L’objectif du projet est la réalisation d’une étude topo-bathymétrique et sédimentaire dans le Gandiolais, en s’intéressant notamment à la morphologie du fond, à la dynamique sédimentaire, et l’étude des courants dans la zone amont et aval de Pilote Barre.

## Etude bathymétrique de la Lagune de Somone (Associé à l'Université Gaston Berger / Janvier 2015 - Décembre 2015)
L’objectif du projet est la réalisation d’une étude visant à mieux connaître les conditions écologiques et sédimentaires prévalant dans la lagune de Somone dans la région de Thiès du Sénégal. Plus spécifiquement, cette étude consiste à mener une campagne de collecte de relevés bathymétrique, de toute la lagune et d’une partie de la rivière Somone en vue de décider sur le dragage éventuel à conduire.

## Etude d'impact environnemental et social projet BOTO-SENEGAL (Associé à l'Université Gaston Berger / Janvier 2015 - Novembre 2015)
Caractérisation du régime hydrologique du bassin versant de la Falémé et évaluation de ses disponibilités en eau et de la variation saisonnières de celles-ci dans l'année pour les confronter aux besoins en eau du projet.

## Evaluation du projet BAD 1 du [PEPAM](https://www.globalwaters.org/HowWeWork/Activities/pepam-programme-eau-potable-et-assainissement-millennium-water-and-sanitation){target="_blank"} et du [PAGIRE](http://www.dgpre.gouv.sn/index.php/2018/09/14/le-plan-de-gestion-integree-des-ressources-en-eau-pagire/){target="_blank"} (Associé à l'Université Gaston Berger / Février 2015 - Novembre 2015)
Evaluer le degré de performance des deux projets en fonction de quatre principaux critères (pertinence, efficacité, efficience et durabilité).