---
engine: knitr
title: "Projets en 2023"
format: 
    html:
        toc: true
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: {.justify}
## Etude de la cartographie des sources potentielles de conflits, de coopération ou de paix dans le domaine de l’eau (Associé à l'Université Gaston Berger / Août 2023)

L'étude sur la « Cartographie des facteurs de conflit liés à l'eau dans les bassins transfrontaliers » permettra d'identifier les facteurs les plus susceptibles de conduire à des conflits dans ces bassins ainsi que les acteurs impliqués afin de donner un aperçu des potentielles zones de conflits liés à l’eau. Ce travail vient en complément aux travaux sur l’eau et la paix et se focalise sur les sources potentielles de conflits liés à l’eau au niveau national et transfrontalier. Cette étude va donc mettre l’accent sur les territoires d’eaux par exemple les bassins versants, les aquifères, et les Unités de Gestion et de Planification (UGP) définies dans le cadre du [PAGIRE](http://www.dgpre.gouv.sn/index.php/2018/09/14/le-plan-de-gestion-integree-des-ressources-en-eau-pagire/){target="_blank"}. La cartographie des facteurs potentiels de conflits permettra d’identifier sur une base spatiale et temporelle, les facteurs et risques et de caractériser les sources potentielles en relation avec les processus de gestion et de résolution en cours.
:::

## Senegal Water Resources management activity (Programme [USAID](https://www.usaid.gov/){target="_blank"} - Associé à l'Université Gaston Berger / Août 2023)

::: {.justify}
L'objectif principal de ce programme de l'USAID est d'augmenter la croissance économique inclusive grâce à une gestion améliorée et plus équitable des ressources en eau pour les générations actuelles et futures. Les partenaires du programmes sont : Chemonics International, [Centre de Suivi Ecologique (CSE)](https://www.cse.sn/){target="_blank"} et [DECLIC](https://declic-ecologique.com/les-aventures-de-declic-ecologique-au-senegal-2-set-a-ndangane/){target="_blank"}. En tant qu'expert associé au [Centre de Suivi Ecologique (CSE)](https://www.cse.sn/){target="_blank"}, je coordonne toute la partie scientifique de la contribution du [Centre de Suivi Ecologique (CSE)](https://www.cse.sn/){target="_blank"} à ce programme de quatre ans (Mai 25, 2023 – Mai 24, 2027)
:::

## Etude des mécanismes d’adaptation des populations au changement climatique en Casamance (Associé à l'Université Gaston Berger / Mai 2023)

::: {.justify}
L’objectif principal de la mission est d’étudier les mécanismes d’adaptation des populations sur les changements climatiques en Casamance. La mission consiste ainsi à contribuer à l’élaboration d’une stratégie mettant l’accent sur la situation actuelle et sur les besoins concernant les activités relatives à l’adaptation au changement climatique et au développement dans les collectivités territoriales partenaires du Projet.
:::

