---
engine: knitr
title: "Mémoires Master I"
format: 
    html:
        toc: true
---

## {{< fa check-double >}} Beye, Abdou (2015). L’efficacité des systèmes d’irrigation dans la vallée du fleuve Sénégal en fonction du niveau de la nappe du Delta
Depuis la réalisation des barrages de Diama et Manantali qui permettent une meilleure disponibilité de l’eau durant toute l’année, la riziculture est de plus en favorisée dans le Delta du fleuve Sénégal. Ce dernier dispose d’un important potentiel de ressources en eau souterraine. Et dans un contexte ou le coût de l’approvisionnement en eau reste élevé, le potentiel en eau souterraine devrait permettre aux paysans de maximiser leurs rendements avec moins de gaspillage. C'est dans ce contexte qu'est entrepris ce travail qui a pour objectif principal d’évaluer la performance des périmètres irrigués dans la vallée du fleuve Sénégal en fonction des fluctuations de la nappe du Delta. Un suivi de la fluctuation du niveau de la nappe et la détermination de la productivité de l'eau dans le périmètre de Ndiaye permettent de conclure au terme de cette étude, que la pluie et l’irrigation sont les principales
causes de la fluctuation de la nappe. [Document {{< fa file-pdf >}}](https://emma.cloud.tabdigital.eu/s/JwEboCLbwC9WT5f){target="_blank"} 

## {{< fa check-double >}} Ndiaye, Alassane (2015). Analyse du régime hydrologique du fleuve gambie a la station de mako
Le présent rapport s’inscrit en droite ligne dans le cadre de nos recherches en Master avec comme sujet de mémoire : Analyse du régime hydrologique du fleuve Gambie à la station de Mako. La variabilité climatique et ses impacts sur les ressources naturelles et en particulier sur les ressources en eau, et une question préoccupante pour les Etats de l’Afrique soudanosahélien et constitue un handicap pour le développement économique (agriculture, énergie hydroélectrique) et le devenir des populations (eau potable, santé) (Konaté, 1993). Pour mieux s’imprégner de ces problématiques, nous avons effectué un stage au niveau de la DGPRE (Direction de la Gestion et de la Planification des Ressource en Eau), Structure rattachée au ministère de l’hydraulique et de l’assainissement du Sénégal. Ce stage effectué, nous a permis non seulement de maitriser certains logiciels de traitement de données et de gestion des ressources en eau (Arcgis, khronostat, l’application arcswat) mais aussi de découvrir le milieu professionnel. Ce fut également l’occasion pour nous de comprendre la mission combien importante que joue la DGPRE dans le cadre de la gestion et de la planification des ressources en eau dont dispose notre pays. [Document {{< fa file-pdf >}}](https://emma.cloud.tabdigital.eu/s/3Ak5bYSixccifME){target="_blank"}

## {{< fa check-double >}} Ndiaye, Papa Malick (2015). Caracterisation du regime pluviometrique recent du bassin versant de la gambie
Ce travail s’inscrit dans le parcours Ecosystème et Environnement de la Section de géographie, qui traite de toutes les questions relatives à l’environnement et à la dynamique des écosystèmes. Il porte sur la thématique suivante : « caractérisation du régime pluviométrique récent du bassin versant de la Gambie ». En effet, depuis le début des années 70, l’Afrique de l’Ouest, en particulier le sahel, a été affecté par une sécheresse qui est connue grâce à sa rigueur, sa durée et son extension (Sircoulon, 1976). Dans ce contexte de variabilité du climat, les régimes pluviométriques connaissent des variations significatives à la fois spatiales et temporelles. Le bassin de la Gambie n’a pas échappé à cette Situation. C’est ainsi que nous avons effectué un stage à la DGPRE. Ce stage a été effectué durant la période du 07 septembre au 08 octobre sous la direction du Dr Boubacar CISSE et avec l’encadrement de M. Bakary Faty. Pour analyser la variabilité pluviométrique, nous avons eu recourt au calcul de l’indice pluviométrique standardisé (IPS) et aux tests de Pettitt, de Lee et Heguinian et la segmentation d’Hubert pour déterminer les ruptures dans les séries et caractériser ainsi la tendance pluviométrique actuelle. [Document {{< fa file-pdf >}}](https://emma.cloud.tabdigital.eu/s/nneaCjKC5bBpkBZ){target="_blank"}


## {{< fa check-double >}} Dieme, Laurent Pascal M. (2014). Modélisation des écoulements du haut bassin du fleuve Sénégal au pas de temps journalier.
L’eau est la source de toute vie. Ainsi, gérer et maîtriser les ressources en eau pour faire face à des besoins de plus en plus croissants est aujourd’hui un défi majeur. Au niveau du haut bassin du fleuve Sénégal, l’insuffisance des chroniques de données hydrologiques fait obstacle à l’estimation et à la connaissance des ressources en eau. En effet, resté pendant longtemps à l’écart des politiques de développement de l’OMVS, la Guinée n’a rejoint cet organisme qu’en 2006 dans le cadre du projet Global Environnemental Food. Cette situation a fait que cette partie guinéenne du bassin du Sénégal n’a pu disposer d’informations hydrologiques permettant des analyses fiables. C’est dans ce contexte que nous avons appliqués le modèle GR4J pour simuler les écoulements du haut bassin afin de produire des séries de données hydrologiques pour une meilleure connaissance de la variation spatiotemporelle de la ressource en eau. Les données utilisées pour effectuer les simulations vont de 1961 à 2004. Dans l’ensemble, les résultats des simulations obtenus au calage sont bons et le modèle reproduit de manière assez satisfaisante les débits observés. [Document {{< fa file-pdf >}}](https://emma.cloud.tabdigital.eu/s/J7zMH6MMmBcW7S5){target="_blank"}

## {{< fa check-double >}} Coly, Ousseynou (2014). Application du modèle WEAP sur la reserve de Bango
WEAP est un outil robuste et facile à utiliser qui favorise une approche intégrée de la planification des ressources en eau. Il fournit une structure compréhensive, flexible et d’utilisation facile pour les analyses des politiques de gestion. L’intérêt et la particularité de ce modèle résident dans le fait qu’il est utilisé pour la planification de l’exploitation de toutes les ressources en eau que ce soit eau de pluie, eau de surface ou eau souterraine. Ainsi, la question qui se pose est comment faire, dans le cadre d’une gestion appropriée d’un système d’eau, pour assurer l’approvisionnement dans le futur, des différents usagers qui interviennent dans la réserve de Bango  tout en connaissant la capacité d’offre future de la réserve. L’application de ce modèle sera perçue non comme étant une alternative au mode de gestion déjà existant au niveau de la réserve d’eau douce de Bango, mais plutôt comme un outil complémentaire de par son approche globale et l’orientation de sa politique. Ainsi, il s’agit dans le cadre de ce travail de prévoir les capacités d’offre future de la réserve en relation avec la demande. Les résultats qui en ressortent devraient intéresser les décideurs et permettre aux gestionnaires de la réserve de Bango de disposer d’informations pour anticiper sur les éventuelles contraintes de pénurie. [Document {{< fa file-pdf >}}](https://emma.cloud.tabdigital.eu/s/yZeYSjgWHFEpQw5){target="_blank"}