---
engine: knitr
title: "Mémoires Master II"
format: 
    html:
        toc: true
---

## {{< fa check-double >}} Ndiaye Tegue Diagne, (2022). Régionalisation des paramètres du modèle GR2M dans le bassin de la Gambie.
Les services hydrologiques nationaux peinent à assurer un suivi adéquat des cours d'eau en raison d'un manque de ressources financières et humaines. La connaissance de la ressource est donc limitée par l’inaccessibilité des données hydro-climatiques observées, leur caractère lacunaire et la faible densité spatiale des stations de mesure. Ainsi l’objectif de cette présente étude est d’estimer les apports en eau dans le bassin versant du fleuve Gambie via une régionalisation des paramètres du modèle hydrologique GR2M. La méthode de régionalisation s’appuie dans un premier temps sur la connaissance des jeux de paramètres sur les bassins dont on dispose des données hydrologiques, pour, dans un second temps prévoir les jeux de paramètres sur des bassins non jaugés. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/dQ7XgMajLSkkj2s){target="_blank"}

## {{< fa check-double >}} Diop, Serigne Bassirou (2022). Evaluation, calibration et analyse des tendances de l’évapotranspiration de référence (ET~0~) dans les bassins des fleuves Casamance et Gambie.
La méthode de Penman-Monteith (FAO56-PM) est recommandée pour estimer l’ET~0~ dans n’importe quel contexte climatique. Toutefois, son application est limitée dans certaines régions par l’indisponibilité et la difficulté d’accés aux données. Dans ce contexte, l’alternative est d’utiliser des méthodes d’estimation de l’ET~0~ intégrant moins de variables climatiques. Ce travail a trois objectifs : (1) évaluer la performance de vingt méthodes d’estimation de l’ET~0~, (2) calibrer/valider les meilleurs méthodes pour les adapter aux contextes climatiques des bassins de la Casamance et de la Gambie et (3) analyser les tendances annuelles et saisonnières de l’ET~0~ ainsi que sa sensibilité aux variables climatiques. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/HGpLm4drda4iNGX){target="_blank"}

## {{< fa check-double >}} Ka, Ameth (2020). Optimisation du réseau pluviométrique dans le bassin du fleuve Sénégal
Il est aussi important de noter que l’OMVS (Organisation pour la Mise en Valeur du Fleuve Sénégal) dans le cadre de la gestion des ressources en eau du fleuve et de la prévision des crues en temps réel se trouve souvent confronter à un problème de disponibilité de l’information pluviométrique (A. BODIAN, 2016). En effet, l’accès difficile à ces informations est parfois lié à une certaine forme de réticence de la part des gestionnaires de bases de données météorologiques des pays du bassin (Guinée Conakry, Mali, Sénégal et la Mauritanie) (A.
BODIAN, 2016). Donc, il est indispensable de disposer de réseaux de mesures et/ou de surveillance du milieu, efficaces permettant de fournir des données hydrométéorologiques fiables. Ainsi l’optimisation des réseaux de données pluviométriques et la gestion à long terme des ressources en eau dans le bassin du fleuve Sénégal sont
indispensables, tant pour améliorer son environnement que pour assurer le bon fonctionnement des activités liées à l’eau. Des lors, ce travail a pour but de proposer un réseau pluviométrique optimal minimal qui aura une densité suffisante et une répartition spatiale adéquate pour permettre une connaissance de la pluviométrie à partir des stations de références du bassin. Cela permettra de réduire les besoins en données de l’OMVS. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/TCLkN3QFjYjeDjT){target="_blank"}

## {{< fa check-double >}} Goudiaby, Omar (2019). Impact de la variabilite pluviometrique sur la riziculture pluviale dans la commune de djinaky (departement de bignona)
En Casamance, les activités socio-économiques telle que la riziculture dépendent essentiellement de la pluviométrie. En ce sens, la variabilité pluviométrique observée depuis les années 1970 a causé des dommages environnementaux qui se traduisent par la baisse de la fertilité des terres et l’improductivité des milliers d’hectares de vallées salinisées ou acidifiées en Basse Casamance (PADERCA, 2005). Raison pour laquelle la baisse généralisée de la pluviométrie touche fortement les sociétés diolas entièrement rizicoles qui accusent une fréquence de plus en plus importante de mauvaises récoltes (Sambou, 2014 et 2015). À cet effet, la commune de Djinaky située en Basse-Casamance n’échappe pas à cette situation climatique et ses impacts qui ont bouleversé la vie sociale et économique des populations rurales (Diédhiou, 2016). Dans ce contexte, les populations locales ont développé diverses stratégies d’adaptation en guise de réponse aux problèmes dus au changement climatique (PLDCRD, 2004). L’objectif principal de cette étude est de caractériser les impacts de la sécheresse sur la riziculture pluviale en Casamance. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/xR7Mq59pckMNm2E){target="_blank"}

## {{< fa check-double >}} Diatta, Marie Chantal (2018). Impacts des changements d'etats de surface sur la reponse hydrologique du haut bassin de la casamance
Le changement récent des fonctionnements hydrodynamique et hydrologique des bassins versants constitue un enjeu scientifique majeur dans le contexte climatique actuel. On constate, en effet, depuis les années 1970, une hausse des écoulements des rivières d’Afrique de l’Ouest sahélienne et subdésertique où les pluies annuelles sont inférieures à 750 mm (Amogu et al., 2010, Mahé & Paturel, 2009). Cet accroissement des écoulements, qui se traduit souvent par des crues précoces et intenses, s’est paradoxalement produit durant la période de sécheresse. Ce phénomène, qualifié de « paradoxe du Sahel » apparait préférentiellement dans des zones caractérisées par une diminution du couvert végétal et une extension des surfaces cultivées et des surfaces dégradées (Albergel et Valentin, 1991). Le paradoxe du Sahel semble concerner l’essentiel de la bande sahélienne de la Mauritanie au Lac Tchad (Descroix et al.,2013). Dès lors, l’étude de l’évolution des états de surface dans le haut bassin de la Casamance s’avère intéressante car elle permettra de vérifier si ce paradoxe sahélien prévaut dans cette zone. L’objectif principal de notre étude est d’étudier à travers la télédétection, les évolutions des états de surface du haut bassin de la Casamance avant et après sécheresse. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/HGpLm4drda4iNGX){target="_blank"}

## {{< fa check-double >}} Sow, Moussa (2018). Analyse des caractéristiques des températures journalières dans le bassin du fleuve Sénégal
Ce travail d’étude et de recherche s’inscrit dans le cadre du mémoire de master II de géographie dans le parcours « Ecosystème et Environnement » de la section de Géographie de l’Université Gaston de Saint-Louis. Il aborde dans le contexte des changements climatiques la question des extrêmes de températures journalières dans le bassin du fleuve Sénégal. La compréhension de l’évolution des températures est un fondamentale en raison des divers implications et conséquences de celles-ci avec les autres paramètres climatiques. Le but de ce travail est de caractériser l’évolution des températures journalières dans le bassin du fleuve Sénégal. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/SHpnqBr8G7X5nN6){target="_blank"}

## {{< fa check-double >}} Badji, Ousmane (2017). Analyse des impacts environnementaux et socio-économiques du barrage de Guidel et des nouvelles stratégies de revalorisation des terres dans la vallée de Guidel (Basse Casamance).
La basse Casamance a été durement éprouvé par le phénomène de la baisse importante de la pluviométrie. La baisse de la pluviométrie et de l’écoulement fluvial a eu pour conséquences : l’invasion des eaux marines dans tout le réseau hydrographique, la baisse généralisée du niveau des nappes, la salinisation et l’acidification des vasières occupées par la mangrove qui a disparu sur de grandes étendues (DACOSTA, 1989). De nombreuses rizières, aussi bien salées (zones de mangrove) que douce (vallées inondées), ont été abandonnées. Ainsi, au plus fort de la période sèche, au début des années 80, en basse Casamance, deux types d’aménagement ont vu le jour pour limiter les effets de la salinité. D’une part, des grands projets de barrages antisel (Affiniam et Guidel) ont été construits, d’autre part, de petits ouvrages anti-sel ont été édifiés pour arrêter l’entré des eaux salées à l’intérieur des petites vallées alluviales (BARRY, 1986 ; BARRY et al. 1986 ; USAID /SOMIVAC/ISRA, 1985). Le barrage de Guidel qui nous concerne dans le cadre de cette étude, a cessé de fonctionné depuis plus de quinze ans. Et ce non fonctionnement a fait que le milieu physique et humain a connu de profondes mutations. C’est ainsi que nous avons Analysé les impacts environnementaux et socio-économiques du barrage de Guidel et les nouvelles stratégies de revalorisation des terres dans la vallée de Guidel (Basse Casamance). [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/3cGQMzRptNKfpt2){target="_blank"}

## {{< fa check-double >}} Ndaw, Marie Louise N. (2017). Évaluation du volume d’eau distribuée aux producteurs riverains de la CSS pour une meilleure gestion quantitative des ressources en eau : cas de la ferme 3.
Ce mémoire entre dans le cadre d’une étude commanditée par la compagnie sucrière sénégalaise
et qui s’intitule : évaluation du volume d’eau distribué aux producteurs riverains de la CSS pour une meilleure gestion quantitative dans les ressources en eau. L’étude entre dans le cadre de la politique de Responsabilité Sociétale de l’Entreprise (RSE) et vise à déterminer le volume d’eau distribué aux producteurs riverains de ses périmètres afin de mieux contribuer de façon significative à la préservation des ressources en eau. Elle s’est faite à travers un stage qui s’est déroulé d’Aout 2016 à Février 2017 et qui a mobilisé deux étudiants stagiaires qui ont travaillé en binôme au cours des travaux de terrain (un élève ingénieur agronome à l’Ecole National Supérieure d’Agriculture de Thiès ENSA et un étudiant en Master de Géographie à l’Université Gaston Berger de Saint-Louis UGB). C’est ainsi que deux projets de mémoire sont issus de cette étude. Une première soutenue en Juin 2017 à l’ENSA et le présent mémoire de recherche. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/fFa3ZFRE5YNHfEC){target="_blank"}

## {{< fa check-double >}} Ndiaye, Papa Malick (2017). Évaluation de vingt méthodes d'estimation de l'évapotranspiration journalière de référence au Burkina Faso.
Connaître l'évapotranspiration (ET) est très important en matière de planification et de gestion des ressources en eau. À cet effet, plusieurs formules ont été développées pour son estimation. Parmi ces méthodes, celle de PENMAN-MONTEITH est recommandée par la FAO comme modèle de référence du fait de sa performance sous différentes conditions climatiques. Cependant l'application de cette méthode peut être difficile dans certains pays, surtout ceux en voie de développement, où l'accès aux données climatiques est parfois limité. L'une des alternatives est alors d'utiliser des méthodes intégrant moins de variables climatiques.  L'objectif de ce travail est d'évaluer des méthodes d'estimation de l'évapotranspiration, avant de caler et valider les deux meilleures. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/9TYaXfCz928c5JW){target="_blank"} 

## {{< fa check-double >}} Ndiouck, Modou (2017). Evaluation de méthodes d’estimation de l’évapotranspiration dans la vallée du Fleuve Sénégal
L’objectif principal de ce travail est d’étudier l’évapotranspiration dans la vallée du fleuve
Sénégal de 1985 à 2009.  En effet, l’étude de l’évapotranspiration s’avère très complexe dans le contexte de l’Afrique de l’ouest où l’accès aux données climatiques n’est pas chose facile (Diouf et al, 2016). II est cependant important d’évaluer les quantités d’eaux évaporées dans le temps et dans l’espace au niveau de la vallée du fleuve Sénégalafin de mieux gérerles pertes par évapotranspiration pour les besoins de l’agriculture.  Depuis 1950, plusieurs formules ont été développées pour estimer l’évapotranspiration. Dans cette étude, nous avons effectué des analyses de sensibilité de l'évapotranspiration aux variables climatiques afin de choisir les modèles les plus adaptés pour cette thématique. C’est ainsi que nous avons pu retenir les méthodes deDalton (DN) (1802),Trabert (TR) (1896), Jensen and Haise (JH) (1963), WMO(1996) et Irmak et al. (IK) (2003) pour étudier l’évapotranspiration dans la vallée du fleuve Sénégal. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/jx9pZMKE5s7gwGT){target="_blank"}

## {{< fa check-double >}} Ndiaye, Alassane (2016). Validation de cinq produits de pluies satellites dans le bassin versant de la Casamance.
L’estimation des précipitations par satellite revêt un caractère important pour la gestion des ressources en eau. Elle constitue un outil important pour le suivi de la variabilité spatiotemporelle des précipitations. L’objectif visé dans ce travail est d’évaluer le potentiel des estimations de précipitation par satellite dans le bassin versant de la Casamance. Dans ce mémoire, l’évaluation des algorithmes GPCP, TRMM_V7, TRMM_RT, PERSIANN et RFE2 s’appuie sur une base de données pluviométriques dont la fiabilité est assurée par des stations d’observation in-situ. Pour cette étude, ces données satellites ont été d’abord comparées aux mesures faites au sol par 10 stations réparties sur le bassin versant de la Casamance sur la période 2000-2006. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/HHkWgjGmdBNFgKQ){target="_blank"}

## {{< fa check-double >}} Coly, Ousseynou (2015). Variabilité climatique et impacts sur les coefficients de ruissellement dans le bassin du Sénégal et de la Gambie.
L’objectif principal visé dans ce travail est de caractériser l’évolution récente de la pluviométrie dans les bassins de la Gambie et du Sénégal et de mesurer son impact sur les coefficients de ruissellement. L’évolution climatique récente telle que décrite dans les travaux de Bodian (2014) au Sénégal, A. Aliet al. (2008) et de A. Ali et T. Lebel (2009) sur la zone sahélienne, de A.P. Ouoba (2013) sur le Burkina Faso, de P. Ozer et al. (2009) sur le Niger et de A.J. Niang (2008) sur la Mauritanie, serait favorable à une reprise pluviométrique en Afrique de l’ouest. Ainsi, au regard de ces différents travaux, l’on se pose alors la question de savoir si dans le bassin de la Gambie et du Sénégal, l’évolution récente des précipitations marque une reprise pluviométrique, et quel serait son impact sur les coefficients de ruissellement ? L’objectif principal visé dans ce travail est de caractériser l’évolution récente de la pluviométrie dans les bassins de la Gambie et du Sénégal et de mesurer son impact sur les coefficients de ruissellement. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/isbq3DFMta2NcgF){target="_blank"} 

## {{< fa check-double >}} Cissé, Thierno (2015). Estimation de la consommation en eau des cultures de bananeraie à Gouloumbou (Bassin versant de la Gambie)
Dans un contexte de changement des conditions climatiques, de réduction des volumes d’eau disponibles de modification des conditions de vie sociales et économiques, la connaissance des ressources en eau, de leurs différents usages à travers les interactions entre les sociétés et la ressource recèle d’énormes enjeux. Le bassin du fleuve Gambie, la zone de Gouloumbou en particulier, depuis les années 1970, a fait l’objet de plusieurs études (Konaté, 1993 ; Sy, 2008 ; Lamagat et al., 1990 etc…), toutefois ces études sont centrés sur les composantes structurelles du bassin, les questions hydrologiques et certains activités socio-économiques. Ainsi, qu’en est-il de la question des usages des ressources en eau, du ratio demande agricole de l’eau et de la disponibilité de l’eau, de la satisfaction des besoins en eau et des impacts potentiels des usages sur l’évolution future de la ressource ? L’objectif principal de ce travail d’étude est d’estimer la consommation en eau des cultures de bananeraie à Gouloumbou. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/86bcGb28NimpGqR){target="_blank"} 

## {{< fa check-double >}} Dieme, Laurent Pascal M. (2014). Analyse de la capacité du modèle GR4J à simuler les débits caractéristiques observés du Bafing
Resté pendant longtemps à l’écart des politiques de développement de l’OMVS, la Guinée n’a rejoint cet organisme qu’en 2006 dans le cadre du projet Global Environnemental Food. Cette situation a fait que cette partie guinéenne du bassin du Sénégal n’a pu disposer d’informations hydrologiques permettant des analyses fiables. L’usage du modèle pluie-débit constitue un palliatif pour les données hydrologiques lacunaires puisqu’il nous permet de compléter des séries de débit à partir des séries de pluie. Cependant, il est nécessaire d’évaluer le modèle pour voir les paramètres hydrologiques qu’il simule le mieux. On utilise ici le modèle GR4J pour voir quels sont les débits caractéristiques du Bafing les mieux simulés. Les données utilisées pour effectuer les simulations vont de 1961 à 2004. Dans l’ensemble, les résultats des simulations obtenus en calage et en validation sont bons et  modèle reproduit de manière assez satisfaisante l’hydrogramme des débits observés. Cela se confirme avec la simulation des débits caractéristiques. Toutefois, les résultats sont plus mitigés pour les débits caractéristiques d’étiage. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/Ng9ztkQpBPHBNM9){target="_blank"} 