---
engine: knitr
title: "Mémoires (M1) Soutenus"
format: 
    html:
        toc: true
---

## {{< fa check-double >}} Beye, Abdou (2015). L’efficacité des systèmes d’irrigation dans la vallée du fleuve Sénégal en fonction du niveau de la nappe du Delta
Depuis la réalisation des barrages de Diama et Manantali qui permettent une meilleure disponibilité de l’eau durant toute l’année, la riziculture est de plus en favorisée dans le Delta. Ce dernier dispose d’un important potentiel de ressources en eau souterraine. Et dans un contexte ou le cout de l’approvisionnement en eau reste élevé, le potentiel en eau souterraine devrait permettre aux paysans de maximiser leurs rendements avec moins de gaspillage. C'est dans ce contexte qu'est entrepris ce travail qui a pour objectif principal d’évaluer la performance des périmètres irrigués dans la vallée du fleuve Sénégal en fonction des fluctuations de la nappe du Delta. Un suivi de la fluctuation du niveau de la nappe et la détermination de la productivité de l'eau dans le périmètre de Ndiaye permettent de conclure au terme de cette étude, que la pluie et l’irrigation sont les principales
causes de la fluctuation de la nappe. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/JwEboCLbwC9WT5f){target="_blank"} 

## {{< fa check-double >}} Ndiaye, Alassane (2015). Analyse du regime hydrologique du fleuve gambie a la station de mako
Le présent rapport s’inscrit en droite ligne dans le cadre de nos recherches en Master avec comme sujet de mémoire : Analyse du régime hydrologique du fleuve Gambie à la station de Mako. La variabilité climatique et ses impacts sur les ressources naturelles et en particulier sur les ressources en eau, et une question préoccupante pour les Etats de l’Afrique soudanosahélien et constitue un handicap pour le développement économique (agriculture, énergie hydroélectrique) et le devenir des populations (eau potable, santé) (Konaté, 1993). Pour mieux s’imprégner de ces problématiques, nous avons effectué un stage au niveau de la DGPRE (Direction de la Gestion et de la Planification des Ressource en Eau), Structure rattachée au ministère de l’hydraulique et de l’assainissement du Sénégal. Ce stage effectué, nous a permis non seulement de maitriser certains logiciels de traitement de données et de gestion des ressources en eau (Arcgis, khronostat, l’application arcswat) mais aussi de découvrir le milieu professionnel. Ce fut également l’occasion pour nous de comprendre la mission combien importante que joue la DGPRE dans le cadre de la gestion et de la planification des ressources en eau dont dispose notre pays. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/3Ak5bYSixccifME){target="_blank"}

## {{< fa check-double >}} Dieme, Laurent Pascal M. (2014). Modélisation des écoulements du haut bassin du fleuve Sénégal au pas de temps journalier.
L’eau est la source de toute vie. Ainsi, gérer et maîtriser les ressources en eau pour faire face à des besoins de plus en plus croissants est aujourd’hui un défi majeur. Au niveau du haut bassin du fleuve Sénégal, l’insuffisance des chroniques de données hydrologiques fait obstacle à l’estimation et à la connaissance des ressources en eau. En effet, resté pendant longtemps à l’écart des politiques de développement de l’OMVS, la Guinée n’a rejoint cet organisme qu’en 2006 dans le cadre du projet Global Environnemental Food. Cette situation a fait que cette partie guinéenne du bassin du Sénégal n’a pu disposer d’informations hydrologiques permettant des analyses fiables. C’est dans ce contexte que nous avons appliqués le modèle GR4J pour simuler les écoulements du haut bassin afin de produire des séries de données hydrologiques pour une meilleure connaissance de la variation spatiotemporelle de la ressource en eau. Les données utilisées pour effectuer les simulations vont de 1961 à 2004. Dans l’ensemble, les résultats des simulations obtenus au calage sont bons et le modèle reproduit de manière assez satisfaisante les débits observés. [Lire {{< fa file-export >}}](https://emma.cloud.tabdigital.eu/s/J7zMH6MMmBcW7S5){target="_blank"}