---
engine: knitr
title: "Thèses de Doctorat"
format: 
    html:
        toc: true
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: {.justify}
## Diop, Serigne bassirou (2023). Régionalisation des crues en Afrique de l'ouest
Cette thèse, qui débute oficiellement en janvier 2023, porte sur l’analyse fréquentielle des crues en Afrique de l’ouest et associe 3 volets :

1. une analyse locale basée sur les mesures ;
2. une analyse régionale pour tenter d’extrapoler les données sur les crues pour des bassins non jaugés et
3. une analyse prospective des scénarios futurs
:::

La supervision de ce travail de thèse est assurée par : <br><hr> 
{{< fa angle-right >}} Ansoumana BODIAN (Université Gaston Berger de Saint-Louis) <br>
{{< fa angle-right >}} Yves TRAMBLAY (HydroSciences Montpellier)  <br>
{{< fa angle-right >}} Alain DEZETTER (HydroSciences Montpellier). <br>

::: {.justify}
## Goudiaby, Omar (2020). Evaluation des estimations de pluies par satellites pour la modélisation hydrologique dans le bassin du fleuve Sénégal (Afrique de l’Ouest)
Cette thèse porte sur l’évaluation des estimations de pluies par satellites pour la modélisation hydrologique dans le bassin du fleuve Sénégal (Afrique de l’Ouest). À l’échelle de ce bassin, la disponibilité d’observations météorologiques de qualité constitue un enjeu majeur. En effet, les données de mesures au sol sont souvent lacunaires et difficilement accessibles (à cause de leur coût d’acquisition élevé). Cela constitue un handicap pour la connaissance des ressources en eau, notamment l’analyse et la modélisation des évolutions hydrométéorologiques. Dans ce contexte, cette thèse cherche :

1. évaluer les estimations de pluies satellites et réanalyses dans cette zone (hauts bassins Guinéens) et déterminer la pertinence des différents produits disponibles (CHIRPS, MSWEP, TRMM, etc.) et,
2. évaluer la sensibilité respective des modèles hydrologiques à ces sources de données afin de proposer une approche adaptée pour la compréhension et gestion des ressources en eau dans le bassin du fleuve Sénégal.
:::

La supervision de ce travail de thèse est assurée par : <br><hr> 
{{< fa angle-right >}} Ansoumana BODIAN (Université Gaston Berger de Saint-Louis) <br>
{{< fa angle-right >}} Alain DEZETTER (HydroSciences Montpellier). <br>
{{< fa angle-right >}} Andrew OGILVIE (UMR G-EAU Montpellier)  <br>

::: {.justify}
## Diémé, Laurent Pascal (2023). Système de surveillance des inondations à l'échelle de l'agglomération de Dakar
Cette étude, menée dans la périphérie urbaine de l’agglomération de Dakar, vise à proposer une modélisation des écoulements et des débordements des ouvrages à fine résolution (5m) pour des intensités de pluie de période de retour différente. Deux étapes méthodologiques
sont combinées pour atteindre cet objectif :

1. la construction de la topologie de drainage urbain tenant compte des modifications induites par le bâti, les canaux artificiels et les bassins de retenue qui conduisent à des modifications des directions du drainage naturel ; 
2. les simulations des écoulements en temps réel ou en mode projet, par un modèle spatialisé parcimonieux adapté au contexte local couplant un modèle hydrologique (SCS-LR) à l’échelle de petits bassins, avec un modèle hydraulique (Onde cinématique) pour la propagation en réseau des écoulements produits à l’exutoire des bassins.
:::

Cette thèse a été soutenue publiquement par M. Laurent Pascal Malang DIEME le 08 février 2023, devant le jury composé par :<br><hr>
{{< fa angle-right >}} M. Aliou DIOP Professeur (Titulaire UFR SAT/UGB [Président])<br>
{{< fa angle-right >}} M. Harouna KARAMBIRI (Professeur Titulaire 2iE (Burkina Faso) [Rapporteur])<br>
{{< fa angle-right >}} M. Éric GAUME (Ingénieur des ponts, des eaux et des forêts (HDR) Univ. Gustave Eiffel (Nantes) [Rapporteur])<br>
{{< fa angle-right >}} M. Ernest AMOUSSOU Professeur (Titulaire Univ. Parakou (Bénin) [Examinateur])<br>
{{< fa angle-right >}} M. Ousmane NDIAYE (Directeur Météo ANACIM (Sénégal) [Examinateur])<br>
{{< fa angle-right >}} M. Alpha SIDIBE (Directeur-DPGI MEA (Sénégal) [Invité])<br>
{{< fa angle-right >}} M. Ansoumana BODIAN (Maître de Conférences UFR LSH/UGB [Directeur de thèse])<br>
{{< fa angle-right >}} M. Christophe BOUVIER (Directeur de Recherche HSM-IRD (Montpellier) [Directeur de thèse])<br>

::: {.justify}
## Ndiaye, Papa Malick (2021). Evaluation, calibration et analyse des tendances actuelles et futures de l’évapotranspiration de référence dans le bassin du fleuve Sénégal. 
L'objectif de cette thèse est d'évaluer et de calibrer vingt méthodes d'estimation de l'évapotranspiration de référence ET~0~ et d'analyser ses tendances actuelles et futures dans le bassin du fleuve Sénégal. La démarche méthodologique adoptée comporte trois phases : 

1. évaluation et calibration de méthodes d’estimation de l’évapotranspiration de référence (ET~0~) ;
2. analyse de la tendance actuelle de l’ET~0~ sur la période 1984-2017 ainsi que sa sensibilité aux variables climatiques;
3. analyse de la tendance future (2036-2065) de l’ET0 ainsi que sa sensibilité aux variables climatiques à partir des sorties des modèles globaux (MCGs) et régionaux (MCRs). 
:::

Cette thèse a été soutenue publiquement par M. Papa Malick NDIAYE le 23 février 2021, devant le jury composé par :<br><hr>
{{< fa angle-right >}} M. Aliou DIOP (Professeur Titulaire UFR SAT/UGB / [Président]) <br>
{{< fa angle-right >}} M. Amadou KEITA (Maître de Conférences 2ie (Burkina Faso) / [Rapporteur]) <br>
{{< fa angle-right >}} M. Théophile VISCHEL (Maître de Conférences IGE (Grenoble) / [Rapporteur]) <br>
{{< fa angle-right >}} M. Gil MAHE (Directeur de Recherche HSM-IRD (Montpellier) / [Examinateur]) <br>
{{< fa angle-right >}} M. Alain DEZETTER (Chargé de Recherche HSM-IRD / [Membre]) <br>
{{< fa angle-right >}} M. Ansoumana BODIAN (Maître de Conférences UFR LSH/UGB / [Membre])<br>
{{< fa angle-right >}} M. Boubou Aldiouma SY (Professeur Titulaire UFR LSH/UGB / [Directeur de thèse])
