---
engine: knitr
title: "Papiers en 2012"
format: 
  html:
    toc: true
---

{{< include utils.qmd >}} 

## {{< fa user-graduate >}} Bodian, Ansoumana. (2012). Approche par modélisation pluie-débit de la connaissance régionale de la ressource en eau : application au haut bassin du fleuve Sénégal: Thèse de doctorat en Hydrologie continentale soutenue en 2011 à l'Université Cheikh Anta Diop de Dakar. Physio-Géo. 3-5. [https://doi.org/10.4000/physio-geo.2561](https://doi.org/10.4000/physio-geo.2561){target="_blank"} 
De nos jours la gestion des ressources en eau est un besoin qui s’exprime à tous les niveaux (local, régional, national, internationale) du fait des conséquences souvent dramatiques d’une pénurie en eau sur le plan humain, économique et politique. Cependant, l’on ne peut bien gérer une ressource que quand elle est connue. Malheureusement les dernières décennies ont vu une réduction considérable des capacités nationales, des pays qui se partagent le bassin du fleuve Sénégal, d’assurer le suivi hydrologique du fleuve et de ses affluents et de produire une information de qualité adaptée aux besoins des utilisateurs. [Ainsi, la connaissance de la ressource en eau et de ses variations saisonnières au niveau du haut bassin de manière générale et dans la partie guinéenne du bassin en particulier présente des faiblesses à cause des séries de données hydrologiques tronquées ou manquantes. Les chroniques de débit sont souvent lacunaires, discontinues, de courte durée, et en conséquence sont difficilement exploitables pour une analyse hydrologique fiable. Dans ce contexte, l’objectif principal de cette étude est de reconstituer les données hydrométriques surtout dans la partie guinéenne du bassin (ce pays vient de rejoindre l’OMVS en 2006, mais avec des données hydrométriques fragmentaires) en utilisant le modèle GR2M. Ceci permet de disposer de séries chronologiques de débits assez longues pour une meilleure estimation des ressources en eau et de leur fluctuation temporelle. A cette fin, on a procèdé dans un premier temps à une caractérisation physiographique puis pluviométrique du haut bassin. Ensuite, une modélisation hydrologique a permis de réaliser le calage/validation des bassins grâce au modèle hydrologique GR2M sur une période de référence. En fin, nous avons évalué les impacts potentiels d’un changement climatique sur l’évolution des ressources en eau du haut bassin en utilisant les sorties de quatre modèles climatiques (CSMK3, HADCM3, MPEH5 et NCPCM) issues du dernier rapport de IPCC 2007 sous influence du scénario SRES A2. La caractérisation du régime pluviométrique est basée sur une analyse statistique des pluies annuelles, mensuelles et journalières, ensuite une spatialisation des résultats des analyses statistiques a été effectuée. Ces cartes offrent un support de visualisation et de synthèse. Elles permettent de quitter la vision réduite à un point pour une vision globale de la pluie à l’échelle de la zone étudiée. Le calage/validation croisée du modèle a permis de choisir les paramètres qui traduisent le mieux la transformation de la pluie en débit. Une fois ces jeux de paramètres choisis pour chaque bassin, cette version du modèle a été appliquée sur l’ensemble de la série pour simuler les écoulements. Cette opération a permis d’étendre les séries de débits mensuels de trois bassins (Bafing Makana, Dakka Saidou et Sokotoro) de 1923 à 2005. Globalement, le modèle reproduit d’une manière satisfaisante la forme des hydrogrammes observés. Les débits de pointes calculés sont bien situés dans le temps même s’ils sont parfois sous-estimés (particulièrement pour le bassin de Bafing Makana pour la période allant de 1981 à 1985) ou surestimés. Les étiages par contre sont parfaitement reconstitués et on observe une bonne superposition des hydrogrammes des débits observés et calculés. En raison de la variété (taille, de physiographie, des états de surface et des caractéristiques des sols) des bassins, qui leur donne une sensibilité différente aux différents termes du climat, les impacts d’un potentiel changement climatique sont variables d’un bassin à l’autre. Ainsi, par rapport aux données observées, les scénarios utilisés prévoient sur nos bassins des variations d’écoulement moyen annuel qui dépendent étroitement des prévisions de précipitation de chaque modèle climatique.]{.abstract} 

## {{< fa note-sticky >}} Bodian, Ansoumana & Dezetter, Alain & Ardoin-Bardin, Sandra & Dacosta, Honoré. (2012). Impact of climate change on water resources of the Upper basin of the Senegal River. [https://doi.org/10.13140/2.1.3872.0962](https://doi.org/10.13140/2.1.3872.0962){target="_blank"}
The perspective of climate change today raises many questions on the evolution of water resources in western Africa. Indeed, water in these regions is a key aspect for the various human activities such as agriculture, power production or water supply. [In this context, this article proposes an evaluation of the impact of climate change on flows in the upper basin of the Senegal River, at the Sokotoro, Dakka Saidou and Bafing Makana gauging stations. The adopted methodology can be summarized as follows: (i) proposing temperature and/or precipitation scenarios based on climate models outputs; (ii) modelling the studied hydrosystems; (iii) analyzing the response of these hydrosystems under climate constraints; (iv) concluding on the sensitivity of these hydrosystems to future climate conditions.]{.abstract}

## {{< fa note-sticky >}} Bodian, Ansoumana. (2012). Approche par modélisation pluie-débit de la connaissance régionale de la ressource en eau : application au haut bassin du fleuve Sénégal. Carnets de géographes. 4. [https://doi.org/10.4000/cdg.1027](https://doi.org/10.4000/cdg.1027){target="_blank"}
De nos jours la gestion des ressources en eau est un besoin qui s’exprime à tous les niveaux (local, régional, national, internationale) du fait des conséquences souvent dramatiques d’une pénurie en eau sur le plan humain, économique et politique. Cependant, l’on ne peut bien gérer une ressource que quand elle est connue. [Malheureusement les dernières décennies ont vu une réduction considérable des capacités nationales, des pays qui se partagent le bassin du fleuve Sénégal, d’assurer le suivi hydrologique du fleuve et de ses affluents et de produire une information de qualité adaptée aux besoins des utilisateurs. Ainsi, la connaissance de la ressource en eau et de ses variations saisonnières au niveau du haut bassin de manière générale et dans la partie guinéenne du bassin en particulier présente des faiblesses à cause des séries de données hydrologiques tronquées ou manquantes. Les chroniques de débit sont souvent lacunaires, discontinues, de courte durée, et en conséquence sont difficilement exploitables pour une analyse hydrologique fiable... [Lire plus...](https://doi.org/10.4000/cdg.1027){target="_blank"}]{.abstract}

## {{< fa note-sticky >}} Bodian, Ansoumana. (2012). Contribution of rainfall-runoff modeling to the knowledge of water resources : Application to Upper Senegal River basin. CLIMATOLOGIE. 9. [https://www.researchgate.net/publication/264040247_...](https://www.researchgate.net/publication/264040247_Contribution_of_rainfall-runoff_modeling_to_the_knowledge_of_water_resources_Application_to_Upper_Senegal_River_basin){target="_blank"}
The knowledge of water resources and their seasonal variations in the upstream basin of the Senegal River in general and its Guinean part in particular is weak because of missing or too short hydrological time series. Streamflow series often show gaps, are non continuous or too short and consequently are difficult to use for reliable hydrological analysis. Thus the objective of this work was to simulate and extend hydrological data as much as possible, using the GR2M rainfall-runoff model.