---
engine: knitr
title: "Papiers en 2014"
format: 
  html:
    toc: true
---

{{< include utils.qmd >}}

## {{< fa note-sticky >}} Ansoumana Bodian, (2014). « Caractérisation de la variabilité temporelle récente des précipitations annuelles au Sénégal (Afrique de l'Ouest) », Physio-Géo, Volume 8 | -1, 297-312. [https://doi.org/10.4000/physio-geo.4243](https://doi.org/10.4000/physio-geo.4243){target="_blank"}
Les années humides de la décennie 1990 ont réduit l'extension de la zone touchée par la sécheresse. Mais des études ont montré que le déficit pluviométrique a persisté dans les régions sahéliennes jusqu'à la fin de la décennie 1990. Face aux évolutions en cours, P. OZER et al. considèrent, en 2003, que la continuité de la période de sécheresse, ou au contraire l'identification d'une rupture pluviométrique vers des conditions plus humides, ne pourra se vérifier statistiquement qu'après dix années de données supplémentaires. [C'est dans cette perspective que se situe le présent travail, qui a pour objectif d'analyser la tendance récente des séries pluviométriques annuelles de vingt deux stations réparties sur le territoire sénégalais, avec des données collectées jusqu'en 2013, afin de juger de la persistance ou non de la sécheresse. Les données couvrent la période 1940-2013 et l'approche adoptée comporte les opérations suivantes : (1) critique et comblement des données lacunaires, (2) calcul des indices de pluie standardisés, (3) détection des ruptures au sein des séries pluviométriques par l'application de trois tests (PETTITT, LEE et HEGHINIAN, HUBERT). L'application de ces différents tests aux indices de pluie standardisés (IPS) calculés à partir de l'ensemble des stations et à partir des stations regroupées en fonction de trois zones climatiques (sud-sahélienne, sud-soudanienne et nord-soudanienne) montre deux ruptures (significatives au seuil de 1 % selon t test de STUDENT). La première est comprise entre 1967 et 1969, tandis que la seconde se situe entre 1986 et 1998 selon le test de PETTITT et entre 1992 et 2007 selon les méthodes de LEE et HEGHINIAN et de HUBERT. En analysant chacune des stations, on constate que la seconde rupture se situe en général entre 1998 et 2002. Seule la méthode de segmentation de HUBERT ne détecte pas toujours de seconde rupture, mais l'absence de détection concerne 18 % des stations seulement. On identifie donc une discontinuité vers des conditions humides depuis 1999 (PETTITT) ou 2003 (LEE et HEGHINIAN ; HUBERT), même si les précipitations annuelles restent inférieures à celles d'avant 1970.]{.abstract}

## {{< fa note-sticky >}} Bodian, Ansoumana & Ndiaye, Ousmane. (2014). Variability on Daily Rainfall Characteristics Over Senegal River Basin Before and After Rainfall Shift. [https://doi.org/10.13140/2.1.2536.1929](https://doi.org/10.13140/2.1.2536.1929){target="_blank"}
MOTIVATION : Several studies have attempted to characterize the variability of rainfall in sub-Saharan Africa. These studies showed a clear decrease in annual and monthly totals since the sixties and seventies, but didn't look what rainfall characteristics undergo significant changes. This could be justified by difficulty in acquiring reliable daily data with few gaps (Kouassi et al., 2010). [However, in recent decades, concern for sustainable management of water resources in a context of climatic va-riability has led to creation of basin organizations such as Organization for the Development of the Senegal River (OMVS), Organization for the Development of the Gambia River (OMVG), the Niger River Basin Authority (NBA) etc. To fulfill their mandates, these basin organizations need reliable data. For this purpose, they colla-borate with technical services (meteorological and hydrological) of their member states allowing development of hydrological and climate databases for different scales (annual, monthly, daily and even hourly with rain intensities in some cases). These databases allow today to conduct analysis of climate variability at finer time scales. DATA : The data used in this study came from the National Me-teorological Services from Guinea, Mali, Senegal and Mauritania and have been extracted from the data-base of the OMVS. Data covers four to twenty rainfall stations (Fig. 1). They are of different quality and length (Fig. 2), depending on the country. A reference period, from 1950 to 1998, was chosen based on the data quality. We then calculated the percentage of mis-sing (by missing, we mean same day without data available even during the dry season) in the data series during the period 1950-1998. On the basis of this criterion (Fig. 3) twenty three rainfall stations with less than 5% have been identi-fied as reference stations in this study. The spatial distribution of these stations is shown in Fig. 3.]{.abstract} 

## {{< fa person-chalkboard >}} Bodian, Ansoumana & Dezetter, Alain. (2014). Contribution of rainfall-runoff modeling to the knowledge of water ressource in Senegal. (Conference: International Conference on the Water-Food-Energy Nexus in Drylands: Bridging Science and Policy). [https://www.researchgate.net/publication/264003747_...](https://www.researchgate.net/publication/264003747_Contribution_of_rainfall-runoff_modeling_to_the_knowledge_of_water_ressource_in_Senegal){target="_blank"}
In the upstream basin of the Senegal River in general and its Guinean part in particular, streamflow series often show gaps, are non continuous or too short and consequently are difficult to use for reliable hydrological analysis. Thus the objective of this work was to simulate and extend hydrological data, using the GR2M rainfall-runoff model. [In a first step, after calculating catchment rainfall using three interpolation methods (kriging, spline function and inverse distance weighted), mean potential evapotranspiration and the maximum, minimum and mean water holding capacity (WHC), a sensitivity analysis of the model to rainfall and WHC input data was performed. Hence we could choose the best combination of input data by catchment based on the Nash-Sutcliffe criterion. Then cross calibration-validation tests were performed using the selected input data to choose model parameter sets. Once the parameter set was chosen for each catchment, this model version was applied on the whole series to simulate streamflow.]{.abstract}
