---
engine: knitr
title: "Papiers en 2015"
format: 
  html:
    toc: true
---

{{< include utils.qmd >}}

## {{< fa note-sticky >}} Mbaye, Adama & Dia, Amadou & Diaw, Amadou & Vecchia, Andrea & Bodian, Ansoumana & Faye, Cheikh & Zucchini, Emanuele & Fiorillo, Edoardo & Dièye, El & Breton, Francoise & Dacosta, Honoré & Seppoloni, Irene & Marut, Jean-Claude & Descroix, Luc & Manzelli, Marco & Baeta, Marc & er-Salem, Marie-Christine & Bacci, Maurizio & Diop, Mbaye & Tarchiani, Vieri. (2015). Eaux et sociétés face au changement climatique dans le bassin de la Casamance. [https://www.researchgate.net/publication/291152987_...](https://www.researchgate.net/publication/291152987_Eaux_et_societes_face_au_changement_climatique_dans_le_bassin_de_la_Casamance){target="_blank"}
Actes de l'Atelier scientifique et du lancement de l'initiative « Casamance : un réseau scientifique au service du développement en Casamance » du 15-17 juin 2015 à l'Hôtel Kadiandoumagne de Ziguinchor, Sénégal Eaux et sociétés face au changement climatique dans le bassin de la Casamance. [L'atelier scientifique « Eau et sociétés face au changement climatique dans le bassin de la Casamance » est organisé par le Conseil National des Recherches d'Italie en collaboration avec le LMI (Laboratoire Mixte International IRD/UGB) PATEO (Patrimoines et Territoires de l'Eau), ISRA (Institut Sénégalais de Recherches Agricoles) et l'Université Assane Seck de Ziguinchor. Il se veut une occasion d'échange entre les institutions de recherche actives dans la région pour faire le point sur les recherches récentes sur les changements climatiques et hydrologiques et leurs impacts environnementaux, agricoles et sociaux, y compris les stratégies d'adaptation et de minimisation des risques. Les premiers deux jours de l'atelier scientifique visent à faire le point sur les recherches récentes ou en cours sur les problèmes d'environnement et de sociétés causés par le Changement Climatique et ses effets hydrologiques, avec un focus sur mangrove, riziculture, érosion côtière, salinisation des eaux et des sols, dans le bassin du fleuve Casamance. Le troisième jour, une table ronde est organisée pour lancer l'Initiative Casamance « Un réseau scientifique au service du développement en Casamance » qui vise à harmoniser la demande et l'offre de produits scientifiques au service du développement dans la Région.]{.abstract}

## {{< fa note-sticky >}} Descroix, Luc & Genthon, Pierre & Peugeot, Christophe & Mahe, Gil & Malam Abdou, Moussa & Vandervaere, Jp & Mamadou, I. & Tanimoun, Bachir & Amadou, Ilia & Galle, Sylvie & Vischel, Theo & Quantin, Guillaume & Dacosta, Honoré & Bodian, Ansoumana & Nazoumou, Yahaya & Zannou, Arnaud. (2015). Paradoxes et contrastes en Afrique de l'Ouest : impacts climatiques et anthropiques sur les écoulements. [https://www.researchgate.net/publication/333797357_...](https://www.researchgate.net/publication/333797357_Paradoxes_et_contrastes_en_Afrique_de_l'Ouest_impacts_climatiques_et_anthropiques_sur_les_ecoulements){abstract="_blank"}
Durant la seconde moitié du XXe siècle, l'Afrique de l'Ouest a connu une période d'excédent pluviométrique de 1950 à 1967, puis une période de déficit pluviométrique prolongé et marqué, de 1968 à 1995. Cet épisode de sécheresse est considéré comme l’un des plus importants à l'échelle du climat mondial du XXe siècle (Hulme, 2001). Depuis 1995, la plus grande partie de la région a retrouvé un niveau de pluviométrie intermédiaire ainsi qu’une variabilité interannuelle analogues à ceux de la première moitié du XXe siècle (Descroix et al., 2012). [Lire plus ...](https://www.researchgate.net/publication/333797357_Paradoxes_et_contrastes_en_Afrique_de_l'Ouest_impacts_climatiques_et_anthropiques_sur_les_ecoulements){abstract="_blank"}

## {{< fa note-sticky >}} DIOP, L., BODIAN, A., & DIALLO, D. (2015). Use of atmometers to estimate reference evapotranspiration in Arkansas. African Journal of Agricultural Research, 10(48), 4376-4383. [https://doi.org/10.5897/AJAR2015.10332](https://doi.org/10.5897/AJAR2015.10332) 
Evapotranspiration (ET) data from atmometers were compared against evapotranspiration estimated by the FAO-56 Penman-Monteith equation, recommended method, in order to evaluate the accuracy of atmometers. Measurements by 3 atmometers with grass cover and 3 atmometers with alfalfa cover were compared, for one growing season, to Penman Monteith based grass and alfalfa equation–(ET0~PM~ and ETr~PM~ ,, respectively). [Comparison between cumulative Evapotranspiration measured by atmometers and ET0~PM~ or ETr~PM~ showed that Atmometers, for both grass and alfalfa, underestimate evapotranspiration by 12.5-21 and 15% respectively. The three Atmometers with alfalfa cover give the same cumulative value (636 mm) compared to the atmometers with grass cover which exhibit different results (atmometers 1 and 3 (467 mm) and atmometers 2 gives 419 mm). Correlation between ET from atmometers and ETr~PM~ or ET0~PM~ estimates were generally good. Evaporation from atmometers with alfalfa cover showed the highest correlation to ETr~PM~ (R2 varying from 0.68 to 0.72) whereas evaporation from atmometers with grass cover present the lowest correlation (R2ranges from 0.49 to 0.68). The results indicated that with the proper regression equation and a good calibration, atmometers could be used to estimate ET for crop water requirement where evapotranspiration estimates are not available from weather stations.]{.abstract}

## {{< fa note-sticky >}} Bodian, Ansoumana & Dezetter, Alain & Diop, Lamine. (2015). Evolution des apports en eau au Barrage de Manantali à l'horizon 2050 (Conférence Internationale sur l’Hydrologie des Grands Bassins Fluviaux de l’AfriqueAt: Hammamet, Tunisie du 26 au 30 octobre 2015). [https://doi.org/10.13140/RG.2.1.3561.0967](https://doi.org/10.13140/RG.2.1.3561.0967){target="_blank"}
Ce travail vise à évaluer l’impact du changement climatique sur les apports en eau au barrage de Manantali. La démarche a consisté en : (i) la modélisation des écoulements du Bafing à la station de Bafing Makana ; (ii)l’élaboration de scénarios climatiques à l’horizon 2050 ; (iii) l’évaluation de la sensibilité de l'hydrosystème aux conditions climatiques futures. [Le modèle pluie-débit GR4J a été utilisé, calé et validé au pas de temps journalier sur la période 1961-2004. Les sorties de six modèles climatiques de l’exercice CMIP5 avec les scénarios RCP 4.5 et 8.5 scénarios d’évolution de gaz à effet de serre, ont été utilisées pour produire des grilles journalières de température, d’évapotranspiration potentielle et de précipitations pour la période 2036-2065. En hypothèse moyenne (RCP 4.5), par rapport à la période de référence 1971-2000, trois des six modèles climatiques prévoient une baisse des écoulements moyens annuels variant entre -8.1 % et -33.4 %. En hypothèse pessimiste (RCP 8.5), cinq modèles climatiques prévoient une baisse des écoulements comprise entre -1.3 % et -56.8 %.]{.abstract}

## {{< fa note-sticky >}} Sy, Boubou & Sy, Amadou & Bodian, Ansoumana & Faye, Cheikh Ahmed Tidiane & Niang, Souleymane & Diop, Mariama & Ndiaye, Marietou. (2015). « Brèche » ouverte sur la Langue de Barbarie à Saint-Louis Esquisse de bilan d’un aménagement précipité. [https://www.researchgate.net/publication/280080654_...](https://www.researchgate.net/publication/280080654_Breche_ouverte_sur_la_Langue_de_Barbarie_a_Saint-Louis_Esquisse_de_bilan_d'un_amenagement_precipite/citation/download){target="_blank"}
En octobre 2003, la ville de Saint-Louis allait être engloutie par la montée des eaux du fleuve Sénégal. Il fallait rapidement trouver une solution pour sauver la ville et des vies humaines. C'est ainsi que les pouvoirs publics et les autorités communales ont pris la décision de créer un canal de délestage sur la Langue de Barbarie (LB). [Cette brèche, de 4 m. au départ, a atteint 5200 m. de large en février 2015, changeant les caractéristiques biophysiques de la zone. Les terres du Gandiol qui étaient jadis propices au maraîchage sont affectées par la salinisation à cause de l'intrusion du biseau salé. Les villages de Doun Baba Dièye et de Keur Bernard ont disparu, plusieurs pirogues ont chaviré au niveau de la brèche, entraînant plusieurs pertes en vies humaines. Les riverains de la Lagune de Mboumbaye sont pris au piège des flots de l'océan Atlantique. C'est dans ce contexte qu'une équipe de chercheurs du Laboratoire Leïdi « Dynamiques des territoires et développement » de l'Université Gaston Berger (UGB) de Saint-Louis, s'est engagée pour une meilleure connaissance du phénomène de la brèche et de ses implications. »]{.abstract}

## {{< fa note-sticky >}} Sambou, Hyacinthe & Diaw, Amadou & Bodian, Ansoumana & Sané, Tidiane & Sambou, Bienvenu & Traore, Vieux. (2015). Remote sensing mapping of the rice fields and vegetal cover in the sub-watershed of Ebinkine (Lower Casamance, Senegal). Wulfenia. 22. 363-383. [https://www.researchgate.net/publication/280024704_...](https://www.researchgate.net/publication/280024704_Remote_sensing_mapping_of_the_rice_fields_and_vegetal_cover_in_the_sub-watershed_of_Ebinkine_Lower_Casamance_Senegal{target="_blank"})
Rice lowland Lower Casamance is facing a double bind , climate and soil salinization , noticeable in rice areas sub-basin of Ebinkine which covers an area of 2,429.7 ha. This led to the implementation of anti-salt dams and micro-dams in the valleys. The aim of this work is to study the dynamics of paddy fields and vegetation cover in this sub- Watershed from processing and analysis of satellite images. [The methodology used is mainly based on a supervised classification of Landsat TM satellite images of 1984, 1992 and Landsat ETM + 2000 and 2010 associated with fieldwork. The analysis of the dynamics of land use show that rice fields occupying 615.0 hectares in 1984; 581.1 hectares in 1992; 402.2 hectares in 2000 and 415.8 hectares in 2010. The sharp decline of rice cropping is caused by a rainfall defect, as well as mismanagement of the water after the establishment of micro-dams in the subwatershed in 1996. These have led to a flood of 123.6 hectares of rice paddies in the upstream areas of the watershed. Meanwhile, an increase in shrub-trees-savannah between 2000 and 2010, it is the result of natural regeneration promoted by the expansion of plantations of Anacardium occidentale. However, recent illegal timber exploitation has increased between 2000 and 2010 in the area.]{.abstract}

## {{< fa note-sticky >}} Ansoumana Bodian, Alain Dezetter & Honoré Dacosta (2016) Rainfall-runoff modelling of water resources in the upper Senegal River basin, International Journal of Water Resources Development, 32:1, 89-101, [https://doi.org/10.1080/07900627.2015.1026435](https://doi.org/10.1080/07900627.2015.1026435){target="_blank"}
The streamflow series for the upstream basin of the Senegal River is marked by considerable gaps. The objective of this article is to simulate and extend hydrological data, using the GR2M rainfall-runoff model. A sensitivity analysis of the model to rainfall and water holding capacity input data was performed. [This analysis was performed after calculating catchment rainfall, mean potential evapotranspiration, and maximum, minimum and mean water holding capacity. The best combination of input data was chosen by catchment based on the Nash-Sutcliffe criterion. Then cross calibration-validation tests were performed, using the selected input data to choose model parameter sets.]{.abstract}

## {{< fa note-sticky >}} Descroix, Luc & Genthon, Pierre & Peugeot, Christophe & Mahe, Gil & Malam, Amadou & Vandervaere, M. & Mamadou, I. & Tanimoun, B. & Amadou, I. & Galle, Sylvie & Quantin, Guillaume & Dacosta, H. & Bodian, Ansoumana & Nazoumou, Yahaya & Zannou, A.. (2015). Impacts des changements climatiques sur les eaux souterraines : réduction des émissions, analyse des processus, mesures d'adaptation. 
To read the full-text of this research, you can request a copy directly from the authors [here](https://www.researchgate.net/publication/317327786_Impacts_des_changements_climatiques_sur_les_eaux_souterraines_reduction_des_emissions_analyse_des_processus_mesures_d%27adaptation){target="_blank"}.

## {{< fa note-sticky >}} Descroix, Luc & Diongue Niang, Aïda & Panthou, Gérémy & Bodian, Ansoumana & Sané, Tidiane & Dacosta, Honoré & Malam Abdou, Moussa & Vandervaere, Jp & Quantin, Guillaume. (2015). Evolution récente de la mousson en Afrique de l’Ouest à travers deux fenêtres (Sénégambie et Bassin du Niger Moyen). [https://www.researchgate.net/publication/326475977_...](https://www.researchgate.net/publication/326475977_Evolution_recente_de_la_mousson_en_Afrique_de_l'Ouest_a_travers_deux_fenetres_Senegambie_et_Bassin_du_Niger_Moyen){target="_blank"}
La mousson ouest-africaine rythme le calendrier agricole de toute l’Afrique de l’Ouest ; celui-ci est de plus en plus court au fur et à mesure que l’on se déplace vers le Nord, comme la durée et l’abondance de la mousson diminuent. Après une période de sécheresse de 1968 à 1995, l’Afrique de l’Ouest connaît plutôt depuis la fin du dernier millénaire un retour à des conditions pluviométriques plus humides ; celles-ci, aux latitudes soudano-sahéliennes, sont similaires, en termes de moyenne et de variabilité interannuelle, à celles qui ont été observées de 1900 à 1950. [L’objectif est de montrer en quoi l’évolution pluviométrique récente explique la dynamique hydrologique et agronomique de la région ouest-africaine, en particulier l’occurrence accrue des inondations et le faible regain des rendements agricoles en dépit du retour à une pluviométrie plus favorable. Des méthodes statistiques simples sont utilisées dans deux sous-régions, la Sénégambie et le bassin du Niger Moyen, pour mettre en évidence l’évolution, sur la période 1950-2013, des caractéristiques de la mousson qui ont un intérêt hydrologique et agronomique (cumuls annuels, pluies extrêmes, date de début et de fin et durée de la saison des pluies). On observe que les périodes 1900-1950 et 1995-2015 peuvent être considérées comme des périodes de pluviométrie moyenne, les périodes 1951-1967 et 1968-1995 étant des périodes respectivement humides et sèches. Par ailleurs, on observe une augmentation des jours de pluie de fort cumul bien plus rapide que celle de la pluie elle-même. Enfin, si la saison des pluies est à présent sensiblement plus longue que durant la phase sèche, on observe pourtant ces dernières années dans le Sahel central un retour des « mauvais » hivernages au sens agronomique du terme.]{.abstract}