---
engine: knitr
title: "Papiers en 2016"
format: 
  html:
    toc: true
---

{{< include utils.qmd >}}

## {{< fa note-sticky >}} Ansoumana Bodian, Honoré Dacosta, Réné Ndimag Diouf, El Hadj Ousmane Ndiaye, Anastasie Mendy, (2016). Contribution à la connaissance de l’aléa pluvial au sénégal grâce à la valorisation des données pluviographiques historiques, Climatologie 13 38-46 (2016). [https://doi.org/10.4267/climatologie.1194](https://doi.org/10.4267/climatologie.1194){target=_blank}
Cette note de recherche présente les résultats du programme de dépouillement des diagrammes pluviographiques des principales stations synoptiques du Sénégal qui a duré 6 ans (2001-2006). Ce programme a été entrepris par le laboratoire d’hydro-morphologie du Département de Géographie de l’Université Cheikh Anta Diop de Dakar (UCAD) en collaboration avec l’Agence Nationale de l’Aviation Civile et de la Météorologie (ANACIM), ex Direction de la Météorologie du Sénégal. [Il a permis de sauvegarder et de mettre sous forme numérique une base de données pluviographique opérationnelle à l’échelle du pays. Des courbes Intensité-Durée-Fréquence (IDF) ont ainsi été élaborées pour les stations qui disposent de données suffisantes. Ces courbes IDF peuvent désormais servir au dimensionnement des ouvrages hydrauliques et devront conduire à la définition des plans d’assainissement fiables.]{.abstract}

## {{< fa person-chalkboard >}} Y., Sane & G., Panthou & Bodian, Ansoumana & Vischel, Théo & Dacosta, Honoré & G., Quantin & Lebel, T. & Diongue Niang, Aïda & Ndiaye, Ousmane. (2016). A reliable methodology to infer Intensity-Duration-Frequency (IDF) rainfall curves applied in Senegal (2~eme~ conference internationale Friend/UNESCO/Programme hydrologique international sur l’hydrologie des grands bassins africains : dakar, senegal, 27 novembre – 3 decembre 2016). [https://www.researchgate.net/publication/312305008_...](https://www.researchgate.net/publication/312305008_A_reliable_methodology_to_infer_Intensity-Duration-Frequency_IDF_rainfall_curves_applied_in_Senegal){target="_blank"}
The implementation of water policies and water resources management require relevant tools of hydrologic engineering. In the case of urban floods, which have strong socio-economic impacts, the design of water structures (hydraulic spillways of stormwater, dams, etc) necessarily involves the analysis of sub-daily extreme rainfall series. [It is the main purpose of Intensity-Duration-Frequency (IDF) rainfall curves which aim at estimating rainfall return levels at different time scales. In West Africa, IDF curves are all the more important as the region has faced since the last two decades a concomitant increase of flood hazards, demographic rates, rural exodus and urbanization. However, due to observational or practical limitations, IDF curves are rare in West African countries and the methodologies used to build them often suffer from scientific weaknesses. The main purpose of this study is to estimate IDF curves in Senegal by applying a parsimonious but reliable statistical framework based on both extreme value and fractal theories. The study is based on long sub-daily rain-gauge series collected by the National Weather Service of Senegal (ANACIM). The distribution of intensities is described by a GEV distribution, while a simple scaling factor is used to link the different time scales. Beyond the fact that robust IDF curves are now available for Senegal, the results show interesting features as a clear North-South gradient in the parameters of the GEV distribution (a classical feature of the West-African monsoon) while the scaling parameter is affected by the distance to the ocean.]{.abstract}

## {{< fa person-chalkboard >}} Dezetter, Alain & Bodian, Ansoumana. (2016). Apport des données ERA-Interim à la modélisation des ressources en eau du haut bassin du fleuve Sénégal (2~eme~ conference internationale Friend/UNESCO/Programme hydrologique international sur l’hydrologie des grands bassins africains : dakar, senegal, 27 novembre – 3 decembre 2016). [https://www.researchgate.net/publication/312305012_...](https://www.researchgate.net/publication/312305012_Apport_des_donnees_ERA-Interim_a_la_modelisation_des_ressources_en_eau_du_haut_bassin_du_fleuve_Senegal){target="_blank"}
La disponibilité de données climatiques au pas de temps journalier a fortement diminué ces dernières années en Afrique de l’Ouest et plus particulièrement pour le bassin du fleuve Sénégal à cause de leur coût d'acquisition élevé. De plus, lorsque ces données sont acquises, leur prix de vente les mets hors de portée de la plupart des acteurs du développement. [Dans ce contexte, le suivi indispensable des ressources en eau en vue de leur utilisation optimale, de même que la mise en œuvre d’études d’impacts du changement climatique restent approximatifs ou limités aux données anciennes. Les données de réanalyse ERA-Interim sont accessibles gratuitement sur internet. L’étude présentée ici s’intéresse à l’apport de ces données pour la modélisation des ressources en eau du haut bassin du fleuve Sénégal. Les écoulements d’un des principaux affluents, le Bafing à Bafing-Makana (21 290 km²), sont modélisés au pas de temps journalier à l’aide du modèle conceptuel GR4j. Le modèle est calé et validé sur la période 1961-1997 avec de bons résultats (critère de Nash Sutcliffe de 0.88 en calage et 0.84 en validation). Pour la période plus récente (1998-2004), on examine la possibilité de remplacer les données de pluie et de température au sol par les données ERA-Interim.]{.abstract}

## {{< fa person-chalkboard >}} Wilcox, Catherine & Bodian, Ansoumana & Vischel, Théo & G, Panthou & G, Quantin & Casse, C.. (2016). Detection and attribution of hydrological extremes in West Africa (2~eme~ conference internationale Friend/UNESCO/Programme hydrologique international sur l’hydrologie des grands bassins africains : dakar, senegal, 27 novembre – 3 decembre 2016). [https://www.researchgate.net/publication/312305317_...](https://www.researchgate.net/publication/312305317_Detection_and_attribution_of_hydrological_extremes_in_West_Africa){target="_blank"}
After a period of severe drought in the 1970s and 1980s, the Sahel region of West Africa has witnessed a relative increase in precipitation. It has also been struck by several floods of unprecedented magnitude, in spite of annual rainfall totals remaining below those of previous rainy periods. This study aims to attribute the increased risk of flooding to either land use or precipitation regime changes. [Notably, this study seeks to apply rigorous statistical methods developed for the attribution problem in climate science to the domain of hydrology. Selected methods include fraction of attributable risk (FAR) and optimal fingerprinting. Stochastic rainfall scenarios are generated based on the rainfall climatology of the recent past and are fed into a hydrological model representing surface properties associated with land use changes. The presentation will be focused on how the rainfall simulator is adapted to reflect pertinent findings, such as the evolution of extreme events. Precipitation trends and internal variability are analyzed using the AMMA-CATCH Niger data set (30 stations) and data from national daily rain-gauge networks. The Dargol basin, located on the right bank of the Niger river, is used as a test case. The proposed methodology for the attribution problem can be adapted for application at other sites.]{.abstract}

## {{< fa note-sticky >}} Bodian A, Dezetter A, Deme A, Diop L. Hydrological Evaluation of TRMM Rainfall over the Upper Senegal River Basin. Hydrology. 2016; 3(2):15. [https://doi.org/10.3390/hydrology3020015](https://doi.org/10.3390/hydrology3020015)
The availability of climatic data, especially on a daily time step, has become very rare in West Africa over the last few years due to the high costs of climate data monitoring. This scarcity of climatic data is a huge obstacle to conduct hydrological studies over some watersheds. [In this context, our study aimed to evaluate the capacity of Tropical Rainfall Measuring Mission (TRMM) satellite data to simulate the observed runoffs over the Bafing (the main important tributary of the Senegal River) before their potential integration in hydrological studies. The conceptual hydrological model GR4J (modèle du Génie Rural (Agricultural Engineering Model) à 4 paramètres Journalier (4 parameters Daily)) has been used, calibrated and validated over the 1961–1997 period with rainfall and Potential Evapotranspiration (PET) as inputs. Then, the parameters that best reflect the rainfall-runoff relation, obtained during the cross-calibration-validation phase, were used to simulate runoff over the 1998–2004 period using observed and TRMM rainfalls. The findings of this study show that there is a high consistency between satellite-based estimates and ground-based observations of rainfall. Over the 1998–2004 simulation period, the two rainfall data series show quite satisfactorily results. The output hydrographs from satellite-based estimates and ground-based observations of rainfall coincide quite well with the shape of observed hydrographs with Nash-Sutcliffe Efficiency coefficient (NSE) of 0.88 and 0.80 for observed rainfalls and TRMM rainfalls, respectively.]{.abstract}

## {{< fa note-sticky >}} Diop, L., Bodian, A., & Diallo, D. (2016). Spatiotemporal Trend Analysis of the Mean Annual Rainfall in Senegal. European Scientific Journal, ESJ, 12(12), 231. [https://doi.org/10.19044/esj.2016.v12n12p231](https://doi.org/10.19044/esj.2016.v12n12p231){target="_blank"}
The spatiotemporal trends of annual rainfall in Senegal during 1940 - 2013 were investigated using the Mann–Kendall test and Theil–Sen’s slope estimator. Theil and Sen's slope estimator test was used for finding the magnitude of change over a time period. Inverse Weight Distance (IDW) technique in Arc GIS 10.2 was used to investigate spatial patterns of the trends over the entire country. [For the period 1940-2013, the results of the analysis showed negative trends in annual rainfall at the whole country except for the Bakel station which exhibits a positive trend but not significant. While for the period 1984 - 2013, all the stations show a positive trend with 07 out of 22 stations exhibiting a significant trend at the 95% confidence interval. The spatial distribution of trend during the period 1940- 2013 showed a significant negative trend in the whole study of area except small areas located at the extreme South Est and West as well as North East and West. The trend magnitude varies between -4.41mm/year to 1.34 mm for the period 1940-2013 with a maximum negative magnitude at the Tambacounda station. For 1984-2013, the trend magnitude is positive for the whole country with values varying between 2.67 mm/year at Goudiry and 12.2 mm/year at Ziguinchor. Magnitudes are greater than 5 mm/year, for stations with significant positive trend.]{.abstract}

## {{< fa note-sticky >}} Descroix, Luc & Niang, Aïda & Panthou, Gérémy & Bodian, Ansoumana & Sane, Youssouph & Dacosta, Honoré & Malam Abdou, Moussa & Vandervaere, Jp & Quantin, Guillaume. (2016). Évolution récente de la pluviométrie en Afrique de l’ouest à travers deux régions : la Sénégambie et le Bassin du Niger Moyen. Climatologie. 12. 25-43. 10.4267/climatologie.1105. [https://doi.org/10.4267/climatologie.1105](https://doi.org/10.4267/climatologie.1105){target="_blank"}
La mousson ouest-africaine rythme le calendrier agricole de toute l’Afrique de l’Ouest; celui-ci est de plus en plus court au fur et à mesure que l’on se déplace vers le Nord, comme la durée et l’abondance de la mousson diminuent. Après une période de sécheresse de 1968 à 1995, l’Afrique de l’Ouest connaît plutôt depuis la fin du dernier millénaire un retour à des conditions pluviométriques plus humides; celles-ci, aux latitudes soudano-sahéliennes, sont similaires, en termes de moyenne et de variabilité interannuelle, à celles qui ont été observées de 1900 à 1950. [L’objectif est de montrer en quoi l’évolution pluviométrique récente explique la dynamique hydrologique et agronomique de la région ouest-africaine, en particulier l’occurrence accrue des inondations et le faible regain des rendements agricoles en dépit du retour à une pluviométrie plus favorable. Des méthodes statistiques simples sont utilisées dans deux sous-régions, la Sénégambie et le bassin du Niger Moyen, pour mettre en évidence l’évolution, sur la période 1950-2013, des caractéristiques de la mousson qui ont un intérêt hydrologique et agronomique (cumuls annuels, pluies extrêmes, date de début et de fin et durée de la saison des pluies). On observe que les périodes 1900-1950 et 1995-2015 peuvent être considérées comme des périodes de pluviométrie moyenne, les périodes 1951-1967 et 1968-1995 étant des périodes respectivement humides et sèches. Par ailleurs, on observe une augmentation des jours de pluie de fort cumul bien plus rapide que celle de la pluie elle-même. Enfin, si la saison des pluies est à présent sensiblement plus longue que durant la phase sèche, on observe pourtant ces dernières années dans le Sahel central un retour des « mauvais » hivernages au sens agronomique du terme.]{.abstract}

## {{< fa note-sticky >}} A. Bodian, O. Ndiaye & H. Dacosta (2016): Evolution des caractéristiques des pluies journalières dans le bassin versant du fleuve Sénégal: Aavant et après rupture, Hydrological Sciences Journal, [https://doi.org/10.1080/02626667.2014.950584](https://doi.org/10.1080/02626667.2014.950584){target="_blank"}
L’objectif de cet article est d’analyser à l’échelle du bassin du fleuve Sénégal l’évolution de quatre classes de précipitations journalières, le nombre de jours de pluie et la durée de la saison des pluies. [La méthode consiste à appliquer des tests statistiques d’homogénéité aux séries de pluies annuelles sur la période 1950–1998 pour détecter des ruptures et caractériser l’évolution de ces six variables de part et d’autre des dates de rupture. Les séries de pluie annuelle présentent une rupture entre 1966 et 1970. Les déficits de jours pluvieux de la période après rupture par rapport à celle d’avant varient entre 6,2% à Kédougou et 38,6% à Saint Louis. La classe de pluie de plus de 50 mm (P4) présente les déficits les plus importants qui varient entre 14,8% à la station de Mamou et 66,6% à la station de Nioro du Sahel.]{.abstract}

## {{< fa book >}} Descroix, Luc & Dacosta, Honoré & Sané, Tidiane & Cormier Salem, Marie & Bodian, Ansoumana. (2016). Panorama des conséquences du Changement climatique, à travers la remontée du niveau océanique: érosion côtière et salinisation des eaux et des sols. [https://www.researchgate.net/publication/326542780_...](https://www.researchgate.net/publication/326542780_Panorama_des_consequences_du_Changement_climatique_a_travers_la_remontee_du_niveau_oceanique_erosion_cotiere_et_salinisation_des_eaux_et_des_sols)
L’élévation du niveau de la mer est un fait incontestable ; les marégraphes l’enregistrent depuis plusieurs décennies et depuis les années, les satellites altimétrique permettent de s’en assurer en temps réel et avec une excellente précision. [Lire plus ...](https://www.researchgate.net/publication/326542780_Panorama_des_consequences_du_Changement_climatique_a_travers_la_remontee_du_niveau_oceanique_erosion_cotiere_et_salinisation_des_eaux_et_des_sols){target="_blank"}

## {{< fa note-sticky >}} A. Bodian, O. Ndiaye & H. Dacosta (2016) Evolution des caractéristiques des pluies journalières dans le bassin versant du fleuve Sénégal: Aavant et après rupture, Hydrological Sciences Journal, 61:5, 905-913, [https://doi.org/10.1080/02626667.2014.950584](https://doi.org/10.1080/02626667.2014.950584){target="_blank"}
L’objectif de cet article est d’analyser à l’échelle du bassin du fleuve Sénégal l’évolution de quatre classes de précipitations journalières, le nombre de jours de pluie et la durée de la saison des pluies. [La méthode consiste à appliquer des tests statistiques d’homogénéité aux séries de pluies annuelles sur la période 1950–1998 pour détecter des ruptures et caractériser l’évolution de ces six variables de part et d’autre des dates de rupture. Les séries de pluie annuelle présentent une rupture entre 1966 et 1970. Les déficits de jours pluvieux de la période après rupture par rapport à celle d’avant varient entre 6,2% à Kédougou et 38,6% à Saint Louis. La classe de pluie de plus de 50 mm (P4) présente les déficits les plus importants qui varient entre 14,8% à la station de Mamou et 66,6% à la station de Nioro du Sahel.]{.abstract}