---
engine: knitr
title: "Papiers en 2017"
format: 
    html:
        toc: true
---

{{< include utils.qmd >}}

## {{< fa note-sticky >}} Bodian, Ansoumana. (2017). Discharge prediction in the Upper Senegal River basin using remote sensing data. [https://www.researchgate.net/publication/321171484...](https://www.researchgate.net/publication/321171484_Discharge_prediction_in_the_Upper_Senegal_River_basin_using_remote_sensing_data){target="_blank"}
The Upper Senegal River, West Africa, is a poorly gauged basin. Nevertheless, discharge predictions are required in this river for the optimal operation of the downstream Manantali reservoir, flood forecasting, development plans for the entire basin and studies for adaptation to climate change. Despite the need for reliable discharge predictions, currently available rainfall-runoff models for this basin provide only poor performances, particularly during extreme regimes, both low-flow and high-flow. [In this research we develop a rainfall-runoff model that combines remote-sensing input data and a-priori knowledge on catchment physical characteristics. This semi-distributed model, is based on conceptual numerical descriptions of hydrological processes at the catchment scale. Because of the lack of reliable input data from ground observations, we use the Tropical Rainfall Measuring Mission (TRMM) remote-sensing data for precipitation and the Global Land Evaporation Amsterdam Model (GLEAM) for the terrestrial potential evaporation. The model parameters are selected by a combination of calibration, by match of observed output and considering a large set of hydrological signatures, as well as a-priori knowledge on the catchment. The Generalized Likelihood Uncertainty Estimation (GLUE) method was used to choose the most likely range in which the parameter sets belong. Analysis of different experiments enhances our understanding on the added value of distributed remote-sensing data and a-priori information in rainfall-runoff modelling. Results of this research will be used for decision making at different scales, contributing to a rational use of water resources in this river.]{.abstract}

## {{< fa note-sticky >}} Ndiaye, P. , Bodian, A. , Diop, L. and Djaman, K. (2017) Sensitivity Analysis of the Penman-Monteith Reference Evapotranspiration to Climatic Variables: Case of Burkina Faso. Journal of Water Resource and Protection, 9, 1364-1376. [https://doi.org/10.4236/jwarp.2017.912087](https://doi.org/10.4236/jwarp.2017.912087){target="_blank"}
Sensitivity analysis is important in understanding the effect of each climatic input variable on the variation of the evapotranspiration which is a significant element for hydrological modelling, irrigation programs, and water resources management. [This study investigates the responses of evapotranspiration to the variation of maximum and minimum temperature, solar radiation, wind speed and maximum and minimum relative humidity. Daily data from 1998 to 2012 of eight stations are used. For each climatic variable, a variation of 5% up to ±25% was performed in order to evaluate the sensitivity of the evapotranspiration to the input variables. Results show that evapotranspiration is more sensitive to the variation of solar radiation, maximal temperature and wind speed, respectively.]{.abstract}

## {{< fa note-sticky >}} Koudahe, K. , Djaman, K. , Bodian, A. , Irmak, S. , Sall, M. , Diop, L. , Balde, A. and Rudnick, D. (2017) Trend Analysis in Rainfall, Reference Evapotranspiration and Aridity Index in Southern Senegal: Adaptation to the Vulnerability of Rainfed Rice Cultivation to Climate Change. Atmospheric and Climate Sciences, 7, 476-495. [https://doi.org/10.4236/acs.2017.74035](https://doi.org/10.4236/acs.2017.74035){target="_blank"}
Rainfall and evapotranspiration are two vital elements for food production under rainfed agriculture. This study aims at investigating the combined changes in these variables in the form of aridly index in the southern Senegal. The temporal trends in annual and monthly (from May to October) aridity index, rainfall and evapotranspiration are examined and adaptation strategies to the vulnerability of rainfed rice cultivation to the changes are developed. [The results show a significant decreasing trend in annual rainfall at all study locations for the period 1922-2015. When analyzing the trends in sub-periods, there are two clear patterns in the annual rainfall series: a decreasing trend for the period 1922-1979 and a reversal increasing trend for the period 1980-2015. An increasing trend is also observed in annual reference evapotranspiration. The results reveal that the region will be drier with a significant increase in aridity at the annual and most monthly series. Appropriate adaptation strategies should be implemented to diminish the adverse influence of the increasing aridity on rice productivity for a sustainable agriculture.]{.abstract}

## {{< fa note-sticky >}} Papa Malick Ndiaye, Ansoumana Bodian, Lamine Diop et Koffi Djaman, (2017). « Évaluation de vingt méthodes d'estimation de l'évapotranspiration journalière de référence au Burkina Faso », Physio-Géo, Volume 11 | -1, 129-146. [https://doi.org/10.4000/physio-geo.5369](https://doi.org/10.4000/physio-geo.5369){target="_blank"}
Connaître l'évapotranspiration (ET) est très important en matière de planification et de gestion des ressources en eau. À cet effet, plusieurs formules ont été développées pour son estimation. Parmi ces méthodes, celle de PENMAN-MONTEITH est recommandée par la FAO comme modèle de référence du fait de sa performance sous différentes conditions climatiques. [Cependant l'application de cette méthode peut être difficile dans certains pays, surtout ceux en voie de développement, où l'accès aux données climatiques est parfois limité. L'une des alternatives est alors d'utiliser des méthodes intégrant moins de variables climatiques. L'objectif de ce travail est d'évaluer des méthodes d'estimation de l'évapotranspiration, avant de caler et valider les deux meilleures. Pour ce faire, les données de variables climatiques journalières (Tmax, Tmin, Rs, HRmax, HRmin et u2) de huit stations sur la période 1998-2012 ont été utilisées. L'évaluation des méthodes testées s'est faite en comparant, à l'aide de différents paramètres statistiques, les valeurs qu'elles ont fournies à l'ET0 estimée par la méthode de PENMAN-MONTEITH. Les résultats obtenus montrent que les modèles de H.L. PENMAN (1963), de W. ABTEW (1996), de J.D. VALIANTZAS 1 et 3 (2012-a, 2012-b) et de G.H. HARGREAVES (1975) donnent les meilleurs résultats. Parmi ces cinq méthodes, les deux meilleures ont été retenues pour le calage et la validation. Après calage, la méthode de PENMAN fournit logiquement les estimations les plus proches de l'évapotranspiration de référence, devant celle d'ABTEW.]{.abstract}

## {{< fa note-sticky >}} Lamine Diop, Zaher Mundher Yaseen, Ansoumana Bodian, Koffi Djaman & Larry Brown (2018) Trend analysis of streamflow with different time scales: a case study of the upper Senegal River, ISH Journal of Hydraulic Engineering, 24:1, 105-114. [https://doi.org/10.1080/09715010.2017.1333045](https://doi.org/10.1080/09715010.2017.1333045){target="_blank"}
This study investigates long-term trends of three different time scales including monthly, seasonally and annually at the upper Senegal River basin. Daily streamflows for the period 1961–2014 at Bafing Makana station were used and analyzed to conduct this research. [The serial structural of the different time series (monthly, seasonal, and annual) were investigated in order to detect the presence of autocorrelation. Mann–Kendall test was applied to no autocorrelated series and the Modified Mann–Kendall test for the autocorrelated. Theil and Sen’s slope estimator test was used for finding the magnitude of change and Pettitt test was applied for detecting the most probable change year. Results exhibited a decreasing trend of the annual streamflow yet at the 5% significance level, streamflow series did not have any statistically significant trend for the whole period; however, integrating the different change years, decreasing trend is significant before the first breaking point (1976) and increasing trend is significant from first breaking point to the second change point (1993). For the monthly series, all months exhibit a non-significant decreasing trend except for the month of June. The seasonal series show a decreasing trend which a significant at MAMJ season. Change years were varying accordantly to the scale.]{.abstract}

## {{< fa person-chalkboard >}} Ndiaye, Papa & Bodian, Ansoumana & Diop, Lamine & Djaman, Koffi. (2017). Évaluation des méthodes d’estimation de l’évapotranspiration journalière de référence (ET0) au Burkina Faso (    Conference: Séminaire du collège des écoles doctorales de l'UGB sur la thématique EnvironnementAt: Universite Gaston Berger, Saint Louis-Senegal). [https://www.researchgate.net/publication/316714409_...](https://www.researchgate.net/publication/316714409_Evaluation_des_methodes_d'estimation_de_l'evapotranspiration_journaliere_de_reference_ET0_au_Burkina_Faso){target="_blank"}
Les méthodes de Penman (1963) et Abtew (1996) donnent les meilleures estimations de l’évapotranspiration de référence. L’analyse de sensibilité permet de noter que l’ET0_PM est plus sensible à la variation du rayonnement solaire, suivi par la température maximale et la vitesse du vent. L’humidité relative est la variable qui a moins d’influence sur l’évapotranspiration. Le calage- validation a significativement amélioré l’estimation de l’ET0 par les méthodes d’Abtew (1996) et de Penman (1963).

## {{< fa note-sticky >}} Bodian, Ansoumana & Ahouansou, Mathieu Maurice. (2017). Rapport de diagnostic et d'évaluation des actions pour la mise en place d'un système d'alerte précoce aux crues dans le bassin de l'Ouémé. [https://doi.org/10.13140/RG.2.2.24877.10728](https://doi.org/10.13140/RG.2.2.24877.10728){target="_blank"}
Ces dernières années les inondations sont devenues récurrents au Bénin. En septembre 2010, ce pays a été fortement affecté par des inondations qualifiées d’exceptionnelles, dues à des précipitations diluviennes. Selon les rapports de situation du Comité national de Crise de la mission du Bureau de la coordination des affaires humanitaires des Nations Unies (OCHA), le bilan des inondations de 2010 était lourd puisqu'elles ont affecté, à des degrés divers, 55 communes sur les 77 que compte le Bénin. En outre, 46 personnes ont trouvé la mort, 680 000 sont considérées comme sinistrées dont 180 000 déplacés. [Environ 55 000 habitations se sont écroulées laissant au moins 150 000 personnes sans abris; 425 écoles publiques et 92 centres de santé ont été complètement ou partiellement touchés. Plusieurs secteurs d'activités ont aussi été impactés par les inondations : agriculture, pêche, artisanat, transport, etc. Par exemple dans le domaine agricole, 128 000 hectares de cultures vivrières furent totalement détruits. Dans ce contexte de recrudescence des inondations liée à une intensification du régime hydrologique des différents cours d'eau que compte le pays associé à une vulnérabilité de plus en plus accrue à cause de l'augmentation de la population, il est nécessaire de mettre en place des stratégies et des outils efficaces pour réduire ou atténuer les impacts des inondations. Afin d’y parvenir, il est vital de disposer d'un système d'alerte précoce, qui est un élément essentiel dans la prévention des risques et catastrophes liées aux changements climatiques. Un tel système doit être capable de suivre et de prévoir le comportement des cours d'eaux puis d'émettre des alertes précoces pour permettre aux populations de prendre les dispositions utiles afin de réduire considérablement les conséquences. Ainsi, il permettra d’éviter les pertes en vies humaines et de réduire l’impact matériel et économique des inondations. Disposer d’un tel système qui serait très efficace, nécessite au préalable de faire un état des lieux sur les inondations et les stratégies déjà mises en place dans ces zones pour réduire la vulnérabilité des communautés. Cet état des lieux des Systèmes d'Alerte Précoce (SAP) existants dans le bassin versant de l'Ouémé est l'objectif de cette étude intitulée « Rapport de diagnostic et d'évaluation des actions pour la mise en place d'un système d'alerte précoce aux crues dans le bassin de l'Ouémé ». L'étude a permis dans un premier temps de faire l’historique des inondations dans le bassin versant de l’Ouémé de 1960 à nos jours puis d'évaluer les systèmes d’alerte précoce existants au niveau dudit bassin. L’étude a été repartie en trois volets : revue documentaire, collecte des informations et traitement des données collectées. Le traitement des données a permis d'obtenir des résultats liés à (i) l'historique des inondations dans le bassin ; (ii) la cartographie de la plaine inondable ; et (iii) à l’évaluation du SAP. Pour ce qui est de l'historique des inondations dans le bassin, la variabilité hydroclimatique interannuelle durant les 60 dernières années, révèle que les années 1962, 1963, 1968, 1988, 1997, 1998 et 2010 ont enregistré des cas de fortes inondations. Par contre, c'est le spectre des graves inondations de 2010 qui reste encore vivant dans les mémoires des populations du bassin. Ces inondations ont impacté plusieurs secteurs d'activités. Ainsi, d’après les enquêtes menées, Il ressort que l’agriculture est le secteur le plus impacté par les inondations dans le bassin de l'Ouémé avec des pourcentages de réponse supérieurs à 60 % et atteignant parfois 100 % dans le département du Zou. Ces résultats sont en phase avec le rapport de la banque mondiale qui considère qu'à l'échelle du Bénin, les inondations de 2010 ont plus impacté le secteur agricole. Le deuxième secteur le plus affecté par les inondations est le transport avec un pourcentage de réponse supérieure en moyenne à 35 %. La cartographie de la plaine inondable et des localités étant plus exposées aux inondations a permis d'identifier 99 localités situées dans la basse vallée de l’Ouémé comme étant plus vulnérables aux inondations. Malheureusement, le SAP existant dans le bassin est presque méconnu par les populations à la base d'où son inefficacité pour la mitigation du risque d'inondation. Sur les 7 des 8 départements que compte le bassin, les enquêtes révèlent que plus de 95 % des personnes interrogées ne connaissent pas l'existence d'un SAP. Seul 15 % des enquêtés résidant dans le département de Ouémé affirment avoir connaissance d'un SAP. Ces résultats montrent qu’un effort de communication doit être entrepris pour vulgariser le SAPC qui sera mis en place afin d'améliorer son efficacité. Cependant, ce taux de méconnaissance élevé du SAP-Bénin, par les communautés à la base mérite d'être nuancer. En effet, il pourrait s'expliquer par le fait que les populations à la base voient des activités se dérouler sans pour autant connaitre les initiateurs de ces activités et dans quel cadre elles sont réalisées. Ce qui pourrait expliquer la méconnaissance constatée du SAP-Bénin par ces dernières. Les résultats obtenus montrent aussi qu'il y’a presque pas de centres d’accueil destinés aux sinistrés en période d'inondation. Ces derniers sont obligés de rester chez les parents ou chez les voisins quand leurs habitations sont inondées. Dans le Borgou par exemple, plus de 80 % des enquêtés citent « parents et voisins » comme lieux de logement lors des inondations. A part les parent et voisins, les abris temporaires constituent le deuxième lieu d’hébergement des populations durant la période d'inondation. Ce diagnostic de l'état des lieux montre que le SAP existant dans le bassin de l'Ouémé n'inclut pas dans son fonctionnement les communautés à la base comme cela se doit, d'où la nécessité de mettre en place un SAPC opérationnel qui intègre la dimension communautaire pour une meilleure gestion et une meilleure prise en charge du risque d'inondation au niveau local. Ceci permettra d’éviter les pertes en vies humaines et de réduire l’impact matériel et économique des inondations.]{.abstract}

## {{< fa note-sticky >}} Djaman, Koffi & Rudnick, Daran & Mel, Valere & Mutiibwa, Denis & Diop, Lamine & Sall, Mamadou & Kabenge, Isa & Bodian, Ansoumana & Tabari, Hossein & Irmak, Suat. (2017). Evaluation of Valiantzas’ Simplified Forms of the FAO-56 Penman-Monteith Reference Evapotranspiration Model in a Humid Climate. Journal of Irrigation and Drainage Engineering. 143. [https://doi.org/10.1061/(ASCE)IR.1943-4774.0001191](https://doi.org/10.1061/(ASCE)IR.1943-4774.0001191){target="_blank"}
Unavailability of some meteorological variables especially solar radiation and wind speed is the main constraint for reference evapotranspiration (ETo) estimation using the standard FAO Penman-Monteith (FAO-PM) equation in most developing countries. The application of ETo methods with fewer input requirements is necessary under limited climatic data conditions. [The FAO-PM method under limited data conditions and nine Valiantzas’ equations were evaluated for daily ETo estimation in a humid climate in Uganda. The FAO-PM method with missing relative humidity data performed very well across Uganda, while using the long term local wind speed average values in place of missing wind speed data resulted in inaccurate ETo estimates. Under missing solar radiation measurements, the FAO-PM method showed different performances relative to the locations. When more than one climatic variable are missing, the FAO-PM method yielded poor ETo estimates as compared to the FAO-PM with full climatic data. The performance of the Valiantzas’ equations depends on data requirements: the more the meteorological inputs, the higher ETo accuracy.]{.abstract}