---
engine: knitr
title: "Papiers en 2018"
format: 
    html:
        toc: true
---

{{< include utils.qmd >}}

## {{< fa note-sticky >}} Bodian, Ansoumana, Alain Dezetter, Lamine Diop, Abdoulaye Deme, Koffi Djaman, and Aliou Diop. 2018. "Future Climate Change Impacts on Streamflows of Two Main West Africa River Basins: Senegal and Gambia" Hydrology 5, no. 1: 21. [https://doi.org/10.3390/hydrology5010021](https://doi.org/10.3390/hydrology5010021){target="_blank"}
This research investigated the effect of climate change on the two main river basins of Senegal in West Africa: the Senegal and Gambia River Basins. We used downscaled projected future rainfall and potential evapotranspiration based on projected temperature from six General Circulation Models (CanESM2, CNRM, CSIRO, HadGEM2-CC, HadGEM2-ES, and MIROC5) and two scenarios (RCP4.5 and RCP8.5) to force the GR4J model. [The GR4J model was calibrated and validated using observed daily rainfall, potential evapotranspiration from observed daily temperature, and streamflow data. For the cross-validation, two periods for each river basin were considered: 1961–1982 and 1983–2004 for the Senegal River Basin at Bafing Makana, and 1969–1985 and 1986–2000 for the Gambia River Basin at Mako. Model efficiency is evaluated using a multi-criteria function (Fagg) which aggregates Nash and Sutcliffe criteria, cumulative volume error, and mean volume error. Alternating periods of simulation for calibration and validation were used. This process allows us to choose the parameters that best reflect the rainfall-runoff relationship. Once the model was calibrated and validated, we simulated streamflow at Bafing Makana and Mako stations in the near future at a daily scale. The characteristic flow rates were calculated to evaluate their possible evolution under the projected climate scenarios at the 2050 horizon. For the near future (2050 horizon), compared to the 1971–2000 reference period, results showed that for both river basins, multi-model ensemble predicted a decrease of annual streamflow from 8% (Senegal River Basin) to 22% (Gambia River Basin) under the RCP4.5 scenario. Under the RCP8.5 scenario, the decrease is more pronounced: 16% (Senegal River Basin) and 26% (Gambia River Basin). The Gambia River Basin will be more affected by the climate change.]{.abstract}

## {{< fa note-sticky >}} Catherine Wilcox, Théo Vischel, Gérémy Panthou, Ansoumana Bodian, Juliette Blanchet, Luc Descroix, Guillaume Quantin, Claire Cassé, Bachir Tanimoun, Soungalo Kone, Trends in hydrological extremes in the Senegal and Niger Rivers, Journal of Hydrology, Volume 566, 2018, Pages 531-545, ISSN 0022-1694, [https://doi.org/10.1016/j.jhydrol.2018.07.063](https://doi.org/10.1016/j.jhydrol.2018.07.063){target="_blank"}
In recent years, West Africa has witnessed an increasing number of damaging floods that raise the question of a possible intensification of the hydrological hazards in the region. In this study, the evolution of extreme floods is analyzed over the period 1950–2015 for seven tributaries in the Sudano-Guinean part of the Senegal River basin and four data sets in the Sahelian part of the Niger River basin. [Non-stationary Generalized Extreme Value (NS-GEV) distributions including twelve models with time-dependent parameters plus a stationary GEV are applied to annual maxima of daily discharge (AMAX) series. An original methodology is proposed for comparing GEV models and selecting the best for use. The stationary GEV is rejected for all stations, demonstrating the significant non-stationarity of extreme discharge values in West Africa over the past six decades. The model of best fit most commonly selected is a double-linear model for the central tendency parameter ($\mu$), with the dispersion parameter ($\delta$) modeled as either stationary, linear, or a double-linear. Change points in double-linear models are relatively consistent for the Senegal basin, with stations switching from a decreasing streamflow trend to an increasing streamflow trend in the early 1980s. In the Niger basin the trend in $\mu$ is generally positive since the 1970s with an increase in slope after the change point, but the change point location is less consistent. The recent increasing trends in extreme discharges are reflected in an especially marked increase in return level magnitudes since the 1980s in the studied Sahelian rivers. The rate of the increase indicated by the study results raises urgent considerations for stakeholders and engineers who are in charge of river basin management and hydraulic works sizing.]{.abstract}

## {{< fa note-sticky >}} FATY, B., ALI, A., DACOSTA, H., BODIAN, A., DIOP, S., & DESCROIX, L. (2018). Assessment of satellite rainfall products for stream flow simulation in Gambia watershed. African Journal of Environmental Science and Technology , 12(12), 501-513. [https://academicjournals.org/journal/AJEST/...](https://academicjournals.org/journal/AJEST/how-to-cite-article/7BFB6EA59405){target="_blank"} 
Satellite rainfall estimates (SRE) with high spatial and temporal resolution and large areal coverage provide a potential alternative source to force hydrological models within regions where ground-based measurements are not readily available. The Gambia Basin in West Africa provides a good example of a case where the use of satellite precipitation estimates could be beneficial. This study aims to compare three SRE over a 12-year periods (1998-2010), before and after their integration into the GR4J hydrological model over the Gambia Basin. [The inter-compared products are Climate Hazards Group Infrared Precipitation with Stations (CHIRPS), Precipitation Estimation from Remotely Sensed Information using Artificial Neural Networks-Climate Data Record (PERSIANN-CDR) and TRMM 3B42v7 (Tropical Rainfall Measuring Mission). The calibration and validation of the GR4J model over the Gambia basin using a reference rainfall product (RRP) pointed out a very good performance. The correlation coefficient between simulated and observed daily discharge is higher than 0.8 both for calibration and validation. The inter-comparison of SRE against RRP and using them as forcing data into the calibrated GR4J hydrological model presented some coherence in the product performance. PERSIANN-CDR performs better both when comparing against RRP and when used in GR4J. The low performance of CHIRPS is surprising because it is supposed to be a product that includes ground-base station. This result may also indicate that in areas without ground stations, the CHIRPS is less accurate than other rainfall products that are based only on satellite images. Finally, a bias correction is applied to the SRE using the RRP. The bias correction had significantly improved the product performance. On average, the bias fell from 100 to 1.5% compared to the RRP, but the impact on the error is less significant. When using the corrected SRE in the hydrological model, the impact is very significant both on the bias and error. The overall performance of the different biases that corrected SRE is comparable.]{.abstract}

## {{< fa note-sticky >}} Djaman, Koffi & O’Neill, Michael & Diop, Lamine & Bodian, Ansoumana & Allen, Samuel & Koudahe, Komlan & Lombard, Kevin. (2018). Comparison of some reference evapotranspiration equations under semiarid conditions with limited climatic data (Conference: The 73rd SWCS International Annual Conference: Culture, Climate, and ConservationAt: Albuquerque, New Mexico, USAAffiliation: New Mexico State University). 
Reference evapotranspiration (ETo) is an important parameter in hydrological, agricultural and environmental studies. Accurate estimation of ETo helps to improve water management and increase water productivity and efficiency. While the Penman-Monteith ETo equation enjoys worldwide adoption as the most accurate ETo equation, the number of requested climatic variables makes its application very questionable under limited data conditions. [The objective of this study was to evaluate the Penman-Monteith ETo equation under limited climatic data and 34 simple ETo equations that request few climatic variables. Five weather stations were considered under the semiarid and dry climate across New Mexico for the period of 2009-2017. The Penman-Monteith ETo equation showed good performance under missing solar radiation, relative humidity and wind speed and could still be adapted under limited data conditions across New Mexico. However, it tended to underestimate daily ETo when more than one climatic variable data is missing. Among the simple ETo equations, four of the Valiantzas equations, along with the Makkink, Calibrated Hargreaves, Abtew, Jensen-Haise, and Caprio equations, were the best performing ones compared to the Penman-Monteith equation and could be the best alternative ETo estimation methods. These alternative equations could be used by irrigation managers, producers, engineers and university researchers to improve water management across the dry semiarid and arid zone across New Mexico, as well as other semiarid areas where water is the most limiting factor to food and fiber production.]{.abstract}

## {{< fa note-sticky >}} Sane, Y., Panthou, G., Bodian, A., Vischel, T., Lebel, T., Dacosta, H., Quantin, G., Wilcox, C., Ndiaye, O., Diongue-Niang, A., and Diop Kane, M.: Intensity–duration–frequency (IDF) rainfall curves in Senegal, Nat. Hazards Earth Syst. Sci., 18, 1849–1866, 2018. [https://doi.org/10.5194/nhess-18-1849-2018](https://doi.org/10.5194/nhess-18-1849-2018){target="_blank"}
Urbanization resulting from sharply increasing demographic pressure and infrastructure development has made the populations of many tropical areas more vulnerable to extreme rainfall hazards. Characterizing extreme rainfall distribution in a coherent way in space and time is thus becoming an overarching need that requires using appropriate models of intensity–duration–frequency (IDF) curves. [Using a 14 series of 5 min rainfall records collected in Senegal, a comparison of two generalized extreme value (GEV) and scaling models is carried out, resulting in the selection of the more parsimonious one (four parameters), as the recommended model for use. A bootstrap approach is proposed to compute the uncertainty associated with the estimation of these four parameters and of the related rainfall return levels for durations ranging from 1 to 24 h. This study confirms previous works showing that simple scaling holds for characterizing the temporal scaling of extreme rainfall in tropical regions such as sub-Saharan Africa. It further provides confidence intervals for the parameter estimates and shows that the uncertainty linked to the estimation of the GEV parameters is 3 to 4 times larger than the uncertainty linked to the inference of the scaling parameter. From this model, maps of IDF parameters over Senegal are produced, providing a spatial vision of their organization over the country, with a north to south gradient for the location and scale parameters of the GEV. An influence of the distance from the ocean was found for the scaling parameter. It is acknowledged in conclusion that climate change renders the inference of IDF curves sensitive to increasing non-stationarity effects, which requires warning end-users that such tools should be used with care and discernment.]{.abstract}

## {{< fa note-sticky >}} Hai Tao, Lamine Diop, Ansoumana Bodian, Koffi Djaman, Papa Malick Ndiaye, Zaher Mundher Yaseen, Reference evapotranspiration prediction using hybridized fuzzy model with firefly algorithm: Regional case study in Burkina Faso, Agricultural Water Management, Volume 208, 2018, Pages 140-151, ISSN 0378-3774, https://doi.org/10.1016/j.agwat.2018.06.018. [https://www.sciencedirect.com/science/article/...](https://www.sciencedirect.com/science/article/pii/S0378377418308151){target="_blank"}
Reference Evapotranspiration (ETo) is one of the major components of the hydrological cycle that is very essential in water resources planning, irrigation and drainage management and several other hydrology processes. In irrigation system and design, the prediction of ETo is vital and indispensable for the quantification of crop water needs. This study investigates the capabilities of hybridized fuzzy model with firefly algorithm (ANFIS-FA) for predicting daily reference evapotranspiration over Burkina Faso region. [Metrological information at Bobo Dioulasso, Bur Dedougou, and Ouahigouya stations, in Sahelian, Sudano-Sahelian, and Sudanian zone, are used for modelling development. Six different climatic input variable combinations corresponding to 6 models are inspected. The daily Penman-Monteith reference evapotranspiration for the time-period (1998–2012) are used to train and test the models. Several numerical indicators in addition to Taylor diagram are considered to evaluate the performance of the models. Results indicated that the hybrid ANFIS-FA model outperformed the classical ANFIS-based model for all three stations and the model with full inputs climatic data gave the best results. Furthermore, ANFIS-FA is performed the best for Bur Dedougou (Sahalian-Soudanian region) and less at Ouahigouya (sahalian region). In quantitative terms and for instance Bur Dedougou station, ANFIS-FA model increased the prediction accuracy remarkably (SI = 0.043, R2 = 0.97, MAPE = 0.035 and RMSE = 0.24) compared with ANFIS-based model (SI = 0.068, R2 = 0.89, MAPE = 0.037 and RMSE = 0.378). Results revealed the influence of utilizing nature-inspired firefly algorithm to substantially improve performance of the classical ANFIS model optimization for the applied application. Also, the applied modelling strategy can bring a trustful expert intelligent system for predicting reference evapotranspiration at the west desert of Africa.]{.abstract}

## {{< fa note-sticky >}} Djaman K, Ndiaye PM, Koudahe K, Bodian A, et al. Spatial and temporal trend in monthly and annual reference evapotranspiration in madagascar for the 1980-2010. Int J Hydro. 2018;2(2):110-120. [https://doi.org/10.15406/ijh.2018.02.00058](https://doi.org/10.15406/ijh.2018.02.00058){target="_blank"}
The temporal trend and spatial distribution of reference evapotranspiration was investigated across Madagascar for the period of 1980-2010. Air temperature, relative humidity temperature, relative humidity, solar radiation, and wind speed were collected from 22 weather stations across the country and were used to estimate daily reference evapotranspiration (ETo) by the Penman-Monteith equation. Monthly average daily ETo and the total annual ETo were estimated. [The Mann-Kendall test was used for the temporal trend analysis in monthly average daily ETo and the total annual ETo and the Sen’s method was used to estimate the rate of change in ETo during the study period. The spline interpolation method was used for spatial interpolation of the variation in annual and monthly average ETo. The results showed southwest-north East trend in ETo. Reference evapotranspiration was higher at the western semiarid region than the humid eastern region. ETo peaked during the period of September-October. Annual total ETo varied from 1,081 mm in Andapa at northeast to 2,239 mm in Antsohihy at northwestern coastal region. Overall, there was an increasing trend in annual total ETo; however, the upward trend was significant only at 7 out of 22 weather station sites while monthly ETo did not show consistent trends. This is one of the first comprehensive studies that investigate spatial and temporal dynamics of ETo in Madagascar, which can aid in developing appropriate adaptation strategies to improve crop water use and evaporative losses estimates for maintaining or increasing food production while enhancing water use efficiency in the western semiarid regions of Madagascar. Keywords: Penman-Monteith, reference evapotranspiration, spatio-temporal trend, Madagascar.]{.abstract}

## {{< fa note-sticky >}} Diop, L., Bodian, A., Djaman, K. et al. The influence of climatic inputs on stream-flow pattern forecasting: case study of Upper Senegal River. Environ Earth Sci 77, 182 (2018). [https://doi.org/10.1007/s12665-018-7376-8](https://doi.org/10.1007/s12665-018-7376-8){target="_blank"}
Ideal prediction and modeling of stream-flow and its hydrological applications is extremely significant for decision-making tasks and proper planning of water resource and hydraulic engineering. In the last two decades, the potential of soft computing approaches has increased dramatically in engineering and science problems. In this research, the utility of two soft computing approaches, namely support vector regression (SVR) model and generalized regression neural network (GRNN) is validated to predict one day ahead daily river flow data in the upper Senegal River basin at the Bafing Makana station in West Africa. [The modeling is conducted by including the climatological information in the modelled stream-flow patterns. Correlation procedure is established and applied to obtain the modeling of the input variables with statistically significant lagged datasets at t-1, t-2, and t-3 used as three input combination for each case study scenario. Different statistical indicators are used to evaluate the accuracy of the prediction models. The results show that the accuracy of the models varied by the scenario and the input datasets, where the SVR model yielded the best results for both modelling scenarios. It is also evident that combining the historical stream-flow data with the rainfall and evapotranspiration, can ameliorate substantially the accuracy of the two models for predicting one day ahead stream-flow. A comparison of the optimal SVR and GRNN models in this problem indicates that SVR exhibits superior performance to the GRNN model in estimating the daily stream-flow data, irrespective of the modelling scenario and the datasets that is applied. The findings offer an opportunity to apply SVR model for predicting daily stream-flow, with less data requirement for the investigated Senegal river basin.]{.abstract}