---
engine: knitr
title: "Papiers en 2020"
format: 
    html:
        toc: true
---

{{< include utils.qmd >}}

## {{< fa note-sticky >}} Ndiaye PM, Bodian A, Diop L, Deme A, Dezetter A, Djaman K, Ogilvie A. Trend and Sensitivity Analysis of Reference Evapotranspiration in the Senegal River Basin Using NASA Meteorological Data. Water. 2020; 12(7):1957. [https://doi.org/10.3390/w12071957](https://doi.org/10.3390/w12071957){target="_blank"}
Understanding evapotranspiration and its long-term trends is essential for water cycle studies, modeling and for water uses. Spatial and temporal analysis of evapotranspiration is therefore important for the management of water resources, particularly in the context of climate change. The objective of this study is to analyze the trend of reference evapotranspiration (ET0) as well as its sensitivity to climatic variables in the Senegal River basin. [Mann-Kendall’s test and Sen’s slope were used to detect trends and amplitude changes in ET0 and climatic variables that most influence ET0. Results show a significant increase in annual ET0 for 32% of the watershed area over the 1984–2017 period. A significant decrease in annual ET0 is observed for less than 1% of the basin area, mainly in the Sahelian zone. On a seasonal scale, ET0 increases significantly for 32% of the basin area during the dry season and decreases significantly for 4% of the basin during the rainy season. Annual maximum, minimum temperatures and relative humidity increase significantly for 68%, 81% and 37% of the basin, respectively. However, a significant decrease in wind speed is noted in the Sahelian part of the basin. The wind speed decrease and relative humidity increase lead to the decrease in ET0 and highlight a “paradox of evaporation” in the Sahelian part of the Senegal River basin. Sensitivity analysis reveals that, in the Senegal River basin, ET0 is more sensitive to relative humidity, maximum temperature and solar radiation.]{.abstract}

## {{< fa note-sticky >}} Ndiaye, Papa Malick, Ansoumana Bodian, Lamine Diop, Abdoulaye Deme, Alain Dezetter, and Koffi Djaman. 2020. "Evaluation and Calibration of Alternative Methods for Estimating Reference Evapotranspiration in the Senegal River Basin" Hydrology 7, no. 2: 24. [https://doi.org/10.3390/hydrology7020024](https://doi.org/10.3390/hydrology7020024){target="_blank"} 
Reference evapotranspiration (ET0) is a key element of the water cycle in tropical areas for the planning and management of water resources, hydrological modeling, and irrigation management. The objective of this research is to assess twenty methods in computing ET0 in the Senegal River Basin and to calibrate and validate the best methods that integrate fewer climate variables. [The performance of alternative methods compared to the Penman Monteith (FAO56-PM) model is evaluated using the coefficient of determination (R2), normalized root mean square error (NRMSE), percentage of bias (PBIAS), and the Kling–Gupta Efficiency (KGE). The most robust methods integrating fewer climate variables were calibrated and validated and the results show that Trabert, Valiantzas 2, Valiantzas 3, and Hargreaves and Samani models are, respectively, the most robust for ET0 estimation. The calibration improves the estimates of reference evapotranspiration compared to original models. It improved the performance of these models with an increase in KGE values of 45%, 32%, 29%, and 19% for Trabert, Valiantzas 2, Valiantzas 3, and Hargreaves and Samani models, respectively. From a spatial point of view, the calibrated models of Trabert and Valiantzas 2 are robust in all the climatic zones of the Senegal River Basin, whereas, those of Valiantzas 3 and Hargreaves and Samani are more efficient in the Guinean zone. This study provides information on the choice of a model for estimating evapotranspiration in the Senegal River Basin.]{.abstract}

## {{< fa note-sticky >}} Bodian A, Diop L, Panthou G, Dacosta H, Deme A, Dezetter A, Ndiaye PM, Diouf I, Vischel T. Recent Trend in Hydroclimatic Conditions in the Senegal River Basin. Water. 2020; 12(2):436. [https://doi.org/10.3390/w12020436](https://doi.org/10.3390/w12020436){target="_blank"} 
Analyzing trends of annual rainfall and assessing the impacts of these trends on the hydrological regime are crucial in the context of climate change and increasing water use. This research investigates the recent trend of hydroclimatic variables in the Senegal River basin based on 36 rain gauge stations and three hydrometric stations not influenced by hydraulic structures. [The Man Kendall and Pettitt’s tests were applied for the annual rainfall time series from 1940 to 2013 to detect the shift and the general trend of the annual rainfall. In addition, trends of average annual flow rate (AAFR), maximum daily flow (MADF), and low flow rate (LFR) were evaluated before and after annual rainfall shift. The results show that the first shift is situated on average at 1969 whereas the second one is at 1994. While the first shift is very consistent between stations (between 1966 and 1972), there is a significant dispersion of the second change-point between 1984 and 2002. After the second shift (1994), an increase of annual rainfall is noticed compared to the previous period (1969–1994) which indicates a not significant, partial rainfall recovery at the basin level. The relative changes of hydrologic variables differ based on the variables and the sub-basin. Relative changes before and after first change-point are significantly negative for all variables. The highest relative changes are observed for the AAFR. Considering the periods before and second shifts, the relative changes are mainly significantly positive except for the LFR.]{.abstract}

## {{< fa note-sticky >}} Djaman, Koffi, Komlan Koudahe, Ansoumana Bodian, Lamine Diop, and Papa Malick Ndiaye. 2020. "Long-Term Trend Analysis in Annual and Seasonal Precipitation, Maximum and Minimum Temperatures in the Southwest United States" Climate 8, no. 12: 142. [https://doi.org/10.3390/cli8120142](https://doi.org/10.3390/cli8120142){target="_blank"} 
The objective of this study is to perform trend analysis in the historic data sets of annual and crop season [May–September] precipitation and daily maximum and minimum temperatures across the southwest United States. Eighteen ground-based weather stations were considered across the southwest United States for a total period from 1902 to 2017. [The non-parametric Mann–Kendall test method was used for the significance of the trend analysis and the Sen’s slope estimator was used to derive the long-term average rates of change in the parameters. The results showed a decreasing trend in annual precipitation at 44.4% of the stations with the Sen’s slopes varying from −1.35 to −0.02 mm/year while the other stations showed an increasing trend. Crop season total precipitation showed non-significant variation at most of the stations except two stations in Arizona. Seventy-five percent of the stations showed increasing trend in annual maximum temperature at the rates that varied from 0.6 to 3.1 °C per century. Air cooling varied from 0.2 to 1.0 °C per century with dominant warming phenomenon at the regional scale of the southwest United States. Average annual minimum temperature had increased at 69% of the stations at the rates that varied from 0.1 to 8 °C over the last century, while the annual temperature amplitude showed a decreasing trend at 63% of stations. Crop season maximum temperature had significant increasing trend at 68.8% of the stations at the rates varying from 0.7 to 3.5 °C per century, while the season minimum temperature had increased at 75% of the stations.]{.abstract}

## {{< fa note-sticky >}} Descroix L, Faty B, Manga SP, Diedhiou AB, A. Lambert L, Soumaré S, Andrieu J, Ogilvie A, Fall A, Mahé G, et al. Are the Fouta Djallon Highlands Still the Water Tower of West Africa? Water. 2020; 12(11):2968. [https://doi.org/10.3390/w12112968](https://doi.org/10.3390/w12112968){target="_blank"} 
A large share of surface water resources in Sahelian countries originates from Guinea’s Fouta Djallon highlands, earning the area the name of “the water tower of West Africa”. This paper aims to investigate the recent dynamics of the Fouta Djallon’s hydrological functioning. [The evolution of the runoff and depletion coefficients are analyzed as well as their correlations with the rainfall and vegetation cover. The latter is described at three different space scales and with different methods. Twenty-five years after the end of the 1968–1993 major drought, annual discharges continue to slowly increase, nearly reaching a long-term average, as natural reservoirs which emptied to sustain streamflows during the drought have been replenishing since the 1990s, explaining the slow increase in discharges. However, another important trend has been detected since the beginning of the drought, i.e., the increase in the depletion coefficient of most of the Fouta Djallon upper basins, as a consequence of the reduction in the soil water-holding capacity. After confirming the pertinence and significance of this increase and subsequent decrease in the depletion coefficient, this paper identifies the factors possibly linked with the basins’ storage capacity trends. The densely populated areas of the summit plateau are also shown to be the ones where vegetation cover is not threatened and where ecological intensification of rural activities is ancient.]{.abstract}

## {{< fa note-sticky >}} Ogilvie, Andrew, Jean-Christophe Poussin, Jean-Claude Bader, Finda Bayo, Ansoumana Bodian, Honoré Dacosta, Djiby Dia, Lamine Diop, Didier Martin, and Soussou Sambou. 2020. "Combining Multi-Sensor Satellite Imagery to Improve Long-Term Monitoring of Temporary Surface Water Bodies in the Senegal River Floodplain" Remote Sensing 12, no. 19: 3157. [https://doi.org/10.3390/rs12193157](https://doi.org/10.3390/rs12193157){target="_blank"} 
Accurate monitoring of surface water bodies is essential in numerous hydrological and agricultural applications. Combining imagery from multiple sensors can improve long-term monitoring; however, the benefits derived from each sensor and the methods to automate long-term water mapping must be better understood across varying periods and in heterogeneous water environments. [All available observations from Landsat 7, Landsat 8, Sentinel-2 and MODIS over 1999–2019 are processed in Google Earth Engines to evaluate and compare the benefits of single and multi-sensor approaches in long-term water monitoring of temporary water bodies, against extensive ground truth data from the Senegal River floodplain. Otsu automatic thresholding is compared with default thresholds and site-specific calibrated thresholds to improve Modified Normalized Difference Water Index (MNDWI) classification accuracy. Otsu thresholding leads to the lowest Root Mean Squared Error (RMSE) and high overall accuracies on selected Sentinel-2 and Landsat 8 images, but performance declines when applied to long-term monitoring compared to default or site-specific thresholds. On MODIS imagery, calibrated thresholds are crucial to improve classification in heterogeneous water environments, and results highlight excellent accuracies even in small (19 km2) water bodies despite the 500 m spatial resolution. Over 1999–2019, MODIS observations reduce average daily RMSE by 48% compared to the full Landsat 7 and 8 archive and by 51% compared to the published Global Surface Water datasets. Results reveal the need to integrate coarser MODIS observations in regional and global long-term surface water datasets, to accurately capture flood dynamics, overlooked by the full Landsat time series before 2013. From 2013, the Landsat 7 and Landsat 8 constellation becomes sufficient, and integrating MODIS observations degrades performance marginally. Combining Landsat and Sentinel-2 yields modest improvements after 2015. These results have important implications to guide the development of multi-sensor products and for applications across large wetlands and floodplains.]{.abstract}

## {{< fa note-sticky >}} Alphousseny, Sane & Diop, Lamine & Wane, Yaye & Aminata, Sarr & Diatta, Ibrahima & Diallo, Mariama & Bodian, Ansoumana & Seck, Sidy. (2020). Onion water productivity Assessment in five lowlands in the Niayes area of Senegal. 10. 305-314. [https://doi.org/10.24214/jcbps.D.10.3.30514](https://doi.org/10.24214/jcbps.D.10.3.30514){target="_blank"}
Water productivity monitoring is a key tool for irrigation management in the context of climate change and of areas where water source is very vulnerable. This study is carried out in five (05) lowlands in the North of Niayes: Deur Diabi, Boul Ayni, Lac Kalassane, Nguétiouro, and Ferset Ndoye. [The objective of this study is to assess onion irrigation water productivity in the areas mentioned above. Surveys were carried out with 123 farmers. Water productivity was determined based on applied irrigation volume and onion yields. The results showed that water quantities applied varied between 4,245 m3/ha and 7,485 m3/ha with an average of 7,000 m3/ha. Yields oscillate between 17 and 35 t/ha, with an average of 27.5 t/ha. This gives a water productivity ranging from 3.15 kg/ to 4.27 kg/m3. These results show that onion water productivity in this area is very low and has to be improved. These results can be of great contribution to irrigation optimization.]{.abstract}

## {{< fa note-sticky >}} A. Sane, L. Diop, A. Sarr, Y.D. Wane, I. Diatta, M.D. Diallo, A. Bodian and S.M. Seck (2020); IRRIGATTION WATER PRODUCTIVITY EVALUATION OF TOMATO IN THE NORTHERN NIAYES AREA IN SENEGAL Int. J. of Adv. Res. 8 (Apr). 333-342 (ISSN 2320-5407). [https://www.journalijar.com/article/32127/irrigattion...](https://www.journalijar.com/article/32127/irrigattion-water-productivity-evaluation-of-tomato-in-the-northern-niayes-area-in-senegal/){target="_blank"}
In the Niayes, irrigation of market garden crops is totally ensured by groundwater, which is the only available water source used in irrigation. However, this water source is vulnerable to the development of irrigated agriculture and the impact of climate change. This raises the challenge of optimizing irrigation in this area. [The objective of this study is to evaluate tomato irrigation water productivity in the Lowlands of DeurDiabi, Lac Kalassane, FersetNdoye, BoulAyni and Nguethiouro in the Niayes. In this regard, surveys were carried out with 123 farmers in these five lowlands, focusing on irrigation management at plot level. The volumes of irrigation water supplied per plot and the yields are calculated on the basis of these surveys. Water productivity was determined based on water volumes supplied and yields. Results showed that the volumes of water supplied are very high compared to crop water requirements and yields are relatively low. Water quantities applied per season varied between 3330 m3/ha and 5000 m3/ha and yields varied between 18 t/ha and 27 t/ha. Thus, tomato water productivity is varied between 5.00 and 5.96 kg/m3 with an average of 5.18 kg/m3. These results show that tomato water productivity in this area is very low and has to be improved. These results can be of great contribution to irrigation optimization.]{.abstract}

## {{< fa note-sticky >}} Djaman K, Diop L, Koudahe K, et al. Evaluation of temperature-based solar radiation models and their impact on Penman-Monteith reference evapotranspiration in a semiarid climate. Int J Hydro. 2020;4(2):84-95. [https://doi.org/10.15406/ijh.2020.04.00230](https://doi.org/10.15406/ijh.2020.04.00230){target="_blank"}
Solar radiation is one of the most important climatic parameters that is involved in different environmental, hydrological, agricultural applications while not always measured at all weather stations due to the high equipment and maintenance cost. The objectives of this study were to evaluate the performance and accuracy of twenty temperature based solar radiation models at five weather stations (Alcalde, Fabian Garcia, Farmington, Leyendecker and Tucumcari) in New Mexico and to evaluate the impact of solar radiation prediction on the Penman-Monteith grass reference evapotranspiration (ETo) for the global period of 2009-2017. [New constants of each model at each weather station were retrieved using the optimization procedure Solver in Excel that maximizes the Kling-Gupta Efficiency (KGE). The root mean squared error (RMSE), mean absolute error (MAE), mean bias error (MBE) and the Nash-Sutcliffe model efficiency coefficient (NSE) were used for model performance evaluation. The results showed that the Hargreaves and Samani (1982), improved by Allen 1995, Bristow-Campbell (1984), Hunt et al. (1998), Fan et al. (2018), Hassan et al. (2016), Samani (2000); Nage et al. (2018) 2 and the Richardson et al (2018) models were the most accurate and the best performing ones across all five research sites. The EL-Sabaii, Ert Yal and Clemence models showed the poorest performance at all five stations. The evaluation of the impact of the predicted solar radiation on the Penman-Monteith ETo showed that predicted solar radiation had non-significant effect of the daily ETo with a regression slope varying from 0.978 to 1.022, RMSE from 0.24 to 0.48 mm/day, MAE from 0.15 to 0.31 mm/day and MBE from -0.03 to 0.09 mm/day. All solar radiation models showed best performance at Farmington and Tucumcari while they registered the poorest performance at Alcalde. The Student T-test revealed non-significant differences between the daily ETo using the measured solar radiation data set and the predicted solar radiation by each of the twenty solar radiation models at each weather station. The new models developed in this study could be used to estimate daily solar radiation across the semiarid environment of New Mexico for satisfactory estimation of ETo.]{.abstract}

## {{< fa person-chalkboard >}} Bodian, Ansoumana & Dezetter, Alain & Diop, Lamine & Dacosta, Honoré & Deme, Abdoulaye & Panthou, Gérémy & Vischel, Theo. (2020). Présentation Bodian colloque Saint Louis du 18 au 20 février. [https://doi.org/10.13140/RG.2.2.14778.00964](https://doi.org/10.13140/RG.2.2.14778.00964){target="_blank"}
Le fleuve Sénégal draine un bassin de 300 000 km2, à cheval sur quatre pays que sont, d’amont en aval, la Guinée, le Mali, le Sénégal et la Mauritanie. Il est formé de plusieurs affluents, dont les principaux sont le Bafing, le Bakoye et la Falémé. [Le fleuve Sénégal dispose d'important ressource en eau. En effet, à la station hydrométrique de Bakel, le débit moyen interannuel, sur la période 1950-2014, s’élève à 600 m3/s, soit un volume d’eau annuel de 18 milliards de m3. Cette disponibilité en eau a été fortement impactée par la sécheresse des années 1970 qu'a connu l'Afrique de l'Ouest. Ainsi, au niveau des différent affluents une baisse de 30 à 61 % des écoulements a été observée. Plusieurs efforts (construction de barrages, des digues, mise en place de schéma d'aménagement des eaux et de programme de gestion intégrée des ressources en eau) ont été fait par les Etats riverains à travers l'OMVS pour réduire les impacts néfastes de la sécheresse. Aujourd'hui, dans un contexte de changement climatique, plusieurs autres défis se posent encore aux gestionnaires de la ressources en eau. Ainsi, la communication a pour objectif, de faire dans un premier temps, une synthèse des connaissances sur l'impact de la variabilité et des changements climatiques sur le régime hydrologique du fleuve Sénégal; et ensuite d'énumérer les défis de connaissance majeurs pour une meilleure gestion des ressources en eau.]{.abstract}

## {{< fa note-sticky >}} Diop, L., Samadianfard, S., Bodian, A. et al. Annual Rainfall Forecasting Using Hybrid Artificial Intelligence Model: Integration of Multilayer Perceptron with Whale Optimization Algorithm. Water Resour Manage 34, 733–746 (2020). [https://doi.org/10.1007/s11269-019-02473-8](https://doi.org/10.1007/s11269-019-02473-8){target="_blank"}
Rainfall, as one of the key components of hydrological cycle, plays an undeniable role for accurate modelling of other hydrological components. Therefore, a precise forecasting of annual rainfall is of the high importance. In this regard, several studies have been tried to predict annual rainfall of different climate zones using machine learning and soft computing algorithms. [This study investigates the application of an innovative hybrid method, namely Multilayer Perceptron-Whale Optimization Algorithm (MLP-WOA) to predict annual rainfall comparatively to the ordinary Multilayer Perceptron models (MLP). The models were developed by using 3-Input variables of annual rainfall at lag1, 2 and 3 corresponding to Pt-1, Pt-2 and Pt-3, respectively of two synoptic stations of Senegal (Fatick and Goudiry) in the time period of 1933–2013. 75% of the dataset were utilized for training and the other 25% for testing the studied models Accurateness of the mentioned models was examined using root mean squared error, correlation coefficient, and KlingGupta efficiency. Results showed that MLP-WOA3 and MLP3 using both Pt-1, Pt-2 and Pt-3 as inputs presented the most accurate forecasting in Fatick and Goudiry stations, respectively. In Fatick station, MLP-WOA3 decreased the RMSE value of MLP3 by 18.3% and increased the R and KGE values by 3.0% and 130%, respectively in testing period. But, in Goudiry station, MLP-WOA3 increased the RMSE value of MLP3 by 3.9% and increased the R and KGE values by 10.2% and 91% in testing period. Therefore, it can be realized that the MLP-WOA3 could not able to reduce the RMSE value of correspondent MLP model in Goudiry station. The conclusive results indicated that MLP-WOA slightly improved the accuracy of correspondent MLP models and may be recommended for annual rainfall forecasting.]{.abstract}

