---
engine: knitr
title: "Papiers en 2022"
format: 
    html:
        toc: true
---

{{< include utils.qmd >}}

##  {{< fa note-sticky >}} Laurent Pascal Diémé, Christophe Bouvier, Ansoumana Bodian & Alpha Sidibé (2022). Construction of the drainage topology at fine spatial resolution in an urban environment: example of the Dakar agglomeration (Senegal), LHB, 108:1, [https://doi.org/10.1080/27678490.2022.2061313](https://doi.org/10.1080/27678490.2022.2061313){target="_blank"}
Ces dernières décennies, les villes africaines sont confrontées à des séries d’inondations en lien avec l’urbanisation rapide, l’intensification des fortes pluies et la défaillance du réseau de drainage pluvial. [La prévision de ces inondations constitue un enjeu majeur, et passe par la cartographie précise et lisible des écoulements de surface. Cette étude, menée dans la périphérie urbaine de l’agglomération de Dakar, vise à proposer une méthode de calcul permettant de localiser les débordements du réseau de drainage à l’échelle de l’agglomération, avec des temps de calcul compatibles avec la prévision en temps réel. Après avoir décrit brièvement la méthode, l’article s’attache à montrer comment intégrer les différents objets urbains modifiant les directions de drainage ou les caractéristiques des écoulements (bâti, collecteurs, bassins de retenue) et restituer la topologie du drainage à une échelle fine (5 m). La méthode, basée sur un MNT, est décrite en présentant les algorithmes utilisés ou développés, illustrés par des exemples. Ces algorithmes sont opérationnels dans le logiciel ATHYS et son module Vicair. Cet article sera complété ultérieurement par la description de la modélisation hydrologique et hydraulique associée à cette topologie.]{.abstract}

## {{< fa note-sticky >}} Ibrahima Sy, Ansoumana Bodian, Mamadou Abdoulaye Konté, Lamine Diop, Papa Malick Ndiaye, Sokhna Thiam, Joseph Mouanda; Impact of regional water supply, sanitation et hygiene (WASH) program in Senegal on rural livelihoods and sustainable development. Journal of Water, Sanitation and Hygiene for Development 1 January 2022; 12 (1): 1–15. [https://doi.org/10.2166/washdev.2021.029](https://doi.org/10.2166/washdev.2021.029){target="_blank"}
In 2006, Senegal benefited from the African Development Bank's (AfDB) Rural Water Supply and Sanitation Initiative (RWSSI) a WASH sub-program for 17,100 households in rural areas in the regions of Louga, Ziguinchor and Kolda. [A project results assessment was conducted in 2016 by the AfDB Independent Development Evaluation (IDEV) to measure the sub-program impacts on the living conditions of the communities. This approach allowed the measurement of project impacts based on comparative pre-and post-intervention data, as well as beneficiaries and non-beneficiaries' groups considering collected quantitative data (963 households, 38 schools, 23 health centres and 46 GPS points of infrastructures) and qualitative data (31 individual interviews and 4 focus group discussions). Several analyses (descriptive statistics, correlative analysis, effects and impact analysis with Average Treatment Effect (ATE) and cartographic treatment) were carried out to determine the project's results indicators as well as their overall effects. The results show an access rate of 73% for drinking water among beneficiaries against 6% among non-beneficiaries, and an access rate of 72% for sanitation (improved latrine) in the treatment areas against 33.7% in the control areas. In sub-program focus areas, an increase in the quantity of water used per household by 157 liters, a reduction in water price by 0.072 USD and reduction in time taken to supply drinking water of 65 minutes were observed. Also, it was noted a reduction in arduousness of carrying water by 2 km from the supply point, an increase in the schooling rate of children, especially girls, in income-generating activities, a decrease in the number of sick people avoided by 2 persons and increase in medical treatment avoided were noted. The progress made by the project's achievements demonstrate that improvement in water access, sanitation and hygiene access is one of the main drivers and levers of change and transformation of the households' living conditions in rural areas, often explaining the priority given to this area of intervention within the implementation of the MDGs and SDGs.]{.abstract}

## {{< fa person-chalkboard >}} Bodian, Ansoumana. (2022). The Saint-Louis beach (Senegal) evolution between coastal changes and Senegal River variability. [https://www.researchgate.net/publication/364997811_...](https://www.researchgate.net/publication/364997811_The_Saint-Louis_beach_Senegal_evolution_between_coastal_changes_and_Senegal_River_variability){target="_blank"}
International Ecohydrology Workshop in Tunisia - **ECOTUN 2022** - (Carthage, October 04^th^ to 07^th^ 2022)

## {{< fa note-sticky >}} Papa Malick Ndiaye, Ansoumana Bodian et Serigne Bassirou Diop, (2022). « Paradoxe d'évaporation dans la vallée du fleuve Sénégal », Physio-Géo, Volume 17 | -1, 67-82. [https://doi.org/10.4000/physio-geo.13890](https://doi.org/10.4000/physio-geo.13890){target="_blank"}
L'augmentation des températures dans un contexte de changement climatique devrait être accompagnée par une hausse de l'évaporation et de l'évapotranspiration (ET~0~). Toutefois des études ont montré une baisse de l'évaporation (ou de l'évapotranspiration) dans certaines régions du monde. Ce contraste entre la baisse de l'évaporation et l'augmentation des températures, qui varie en fonction des zones climatiques, est connu sous le nom de "paradoxe d'évaporation". [L'objectif de ce travail est d'en examiner les causes dans la vallée du fleuve Sénégal. Les données climatiques (évaporation, pluie, température, humidité relative, durée d'insolation) observées aux stations de Bakel, Podor, Matam et Saint-Louis, ont été traitées sur la période 1981-2015. La méthodologie comporte : 1/ la détection des ruptures par le test de PETTITT, 2/ l'analyse de la relation entre l'évaporation / évapotranspiration et les variables climatiques par le test de corrélation de PEARSON, 3/ la détection des tendances de l'évaporation / ET0 et des variables climatiques par le test de MANN-KENDALL et la pente de SEN. Les ruptures de l'évaporation et de l'évapotranspiration sont respectivement identifiées dans les années 1990 et 2000. La corrélation de PEARSON montre que l'évaporation et l'ET0 ont pour relation la plus forte, celle avec l'humidité relative. Le test de MANN-KENDALL révèle une baisse significative (p-value ˂ 0,001) de l'évaporation et une évolution nuancée (baisse et hausse) de l'évapotranspiration de référence. Cette baisse de l'évaporation, combinée à une hausse significative de la température, met en évidence l'existence d'un paradoxe d'évaporation dans la vallée du fleuve Sénégal. Ce paradoxe d'évaporation s'explique ici par la hausse significative de l'humidité relative et de la pluviométrie, mais aussi par la baisse significative de la durée d'insolation.]{.abstract}

## {{< fa person-chalkboard >}} Diémé, Laurent Pascal & Bouvier, Christophe & Bodian, Ansoumana & Sidibé, Alpha. (2022). Flood monitoring system in the Dakar agglomeration. (Conference: IAHS Scientific Assembly, 29 May - 3 June 2022 , Montpellier, France In session S2 - Floods : Processes, Forecasts, Probabilities, Impact Assessments and Management) [https://doi.org/10.13140/RG.2.2.24634.67527](https://doi.org/10.13140/RG.2.2.24634.67527){target="_blank"}
This study, carried out in the urban periphery of the Dakar conurbation, aims to propose a calculation method for locating the overflows of the drainage network over the conurbation, with short calculation times compatible with real-time forecasting. Background : In West Africa, most large cities such as Ouagadougou, Accra, Douala, Lagos and Dakar experience a series of floods on an almost annual basis, some of which are particularly disastrous, with impacts on the population, public health, the economy and the living environment. Setting up tools to characterise floods and reduce their impact is essential to facilitate decision-making in this complex and vulnerable context.

## {{< fa person-chalkboard >}} Bodian, Ansoumana & Ndiaye, Papa & Diop, Serigne Bassirou & Diop, Lamine & Dezetter, Alain & Ogilvie, Andrew & Djaman, Koffi. (2022). Evaluation and calibration of alternative methods for estimating reference evapotranspiration in the main hydrosystems of Senegal: Senegal, Gambia and Casamance River Basins. (11th International Assembly of Hydrological Sciences 2022 - IAHS 2022 - S22, Montpellier : Tropical hydrology) [https://www.researchgate.net/publication/361084789_...](https://www.researchgate.net/publication/361084789_Evaluation_and_calibration_of_alternative_methods_for_estimating_reference_evapotranspiration_in_the_main_hydrosystems_of_Senegal_Senegal_Gambia_and_Casamance_River_Basins){target="_blank"}
Reference evapotranspiration (ET0) is an essential parameter for hydrological modeling, irrigation planning and for studying the impacts of climate change on water resources. The Penman-Monteith method is recommended for estimating ET0 under all climatic conditions, but its application is limited in regions where data is difficult to access. [The alternative is to use methods that incorporate fewer climatic parameters. The objective of this work is to evaluate twenty alternative methods using few climate parameters of estimating ET0 and to calibrate/validate the best ones in order to adapt them to the climatic context of the main hydrosystems of Senegal: Senegal, Gambia and Casamance river basins. The KGE and the PBIAS were used to evaluate the performance of the methods. The results show that after calibration/validation the methods of Trabert, Hargreaves, Hargreaves & Samani, Trajkovic and Oudin are the best on for the estimation of the reference evapotranspiration in the Senegal, Gambia and Casamance River Basins.]{.abstract}

## {{< person-chalkboard >}} Ndiaye, Papa & Bodian, Ansoumana & Diop, Serigne Bassirou & Diop, Lamine & Dezetter, Alain & Ogilvie, Andrew & Djaman, Koffi. (2022). Trend analysis of reference evapotranspiration and climate variables in the main hydrosystems of Senegal: Senegal, Gambia and Casamance River Basins. (11th International Assembly of Hydrological Sciences 2022 - IAHS 2022 - S22, Montpellier : Tropical Hydrology) [https://www.researchgate.net/publication/361085043_...](https://www.researchgate.net/publication/361085043_Trend_analysis_of_reference_evapotranspiration_and_climate_variables_in_the_main_hydrosystems_of_Senegal_Senegal_Gambia_and_Casamance_River_Basins){target="_blank"}
Analysis of reference evapotranspiration (ET~0~) trends is essential for understanding the impacts of climate change on water resources. Thus, despite the continuous rise in temperatures, a decrease in evapotranspiration is noted in some parts of the world. This contrast is called the "evaporation paradox" and is thought to be related to the variation in wind speed, relative humidity and solar radiation. [The objective of this work is to analyze the annual and seasonal trends of ET~0~ and climate variables at the scale of the Senegal, Gambia and Casamance river basins. The reanalyse data of NASA/POWER are used over the period 1984-2019. Mann Kendall's test and Sen slope were used to analyze trends in ET0 and climate variables. Results show that on annual scale, ET0 increases significantly in 32% of the Senegal basin and decreases in less than 1% of it. In contrast, in the Casamance and Gambia basins, the annual ET0 drops by 65% and 18%, respectively. On an annual scale, temperature and relative humidity show an increasing trend over all basins while wind speed and radiation decrease significantly. This confirms the existence of the "evaporation paradox" in the three basins. This phenomenon is explained by the increase in relative humidity and the decrease in wind speed and solar radiation.]{.abstract}

## {{< fa note-sticky >}} Laurent Bruckmann, Nicolas Delbart, Luc Descroix & Ansoumana Bodian (2022) Recent hydrological evolutions of the Senegal River flood (West Africa), Hydrological Sciences Journal, 67:3, 385-400, [https://doi.org/10.1080/02626667.2021.1998511](https://doi.org/10.1080/02626667.2021.1998511){target=blank}
The flood of the Senegal River is a resource for the populations of the Senegal Valley, who practice agriculture, fishing and livestock farming in the annually flooded areas. The objective of this paper is to investigate the hydrological evolution of the Senegal River flood since the drought of the 1970s and the construction and management of the Manantali Dam. [To this purpose, the paper analyses the evolution of several parameters of the flood hydrograph and defines the factors that determine the intensity of the flood. Also, a follow-up of the flooded areas in the valley is carried out using remote sensing. The results show that the flood hydrograph has been similar since the 1970s drought, due to the reduction in contributions from the Bafing after the construction of the Manantali Dam. As a result, the high floods depend now on the rainfall pattern in the Sudano-Sahelian zone of the watershed.]{.abstract}

## {{< fa note-sticky >}} Ibrahima Sy, Ansoumana Bodian, Mamadou Abdoulaye Konté, Lamine Diop, Papa Malick Ndiaye, Sokhna Thiam, Joseph Mouanda; Impact of regional water supply, sanitation et hygiene (WASH) program in Senegal on rural livelihoods and sustainable development. Journal of Water, Sanitation and Hygiene for Development 1 January 2022; 12 (1): 1–15. [https://doi.org/10.2166/washdev.2021.029](https://doi.org/10.2166/washdev.2021.029){target="_blank"}
In 2006, Senegal benefited from the African Development Bank's (AfDB) Rural Water Supply and Sanitation Initiative (RWSSI) a WASH sub-program for 17,100 households in rural areas in the regions of Louga, Ziguinchor and Kolda. A project results assessment was conducted in 2016 by the AfDB Independent Development Evaluation (IDEV) to measure the sub-program impacts on the living conditions of the communities. [This approach allowed the measurement of project impacts based on comparative pre-and post-intervention data, as well as beneficiaries and non-beneficiaries' groups considering collected quantitative data (963 households, 38 schools, 23 health centres and 46 GPS points of infrastructures) and qualitative data (31 individual interviews and 4 focus group discussions). Several analyses (descriptive statistics, correlative analysis, effects and impact analysis with Average Treatment Effect (ATE) and cartographic treatment) were carried out to determine the project's results indicators as well as their overall effects. The results show an access rate of 73% for drinking water among beneficiaries against 6% among non-beneficiaries, and an access rate of 72% for sanitation (improved latrine) in the treatment areas against 33.7% in the control areas. In sub-program focus areas, an increase in the quantity of water used per household by 157 liters, a reduction in water price by 0.072 USD and reduction in time taken to supply drinking water of 65 minutes were observed. Also, it was noted a reduction in arduousness of carrying water by 2 km from the supply point, an increase in the schooling rate of children, especially girls, in income-generating activities, a decrease in the number of sick people avoided by 2 persons and increase in medical treatment avoided were noted. The progress made by the project's achievements demonstrate that improvement in water access, sanitation and hygiene access is one of the main drivers and levers of change and transformation of the households' living conditions in rural areas, often explaining the priority given to this area of intervention within the implementation of the MDGs and SDGs.]{.abstract}
